<?php

declare(strict_types=1);

session_start();

require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Domain\Order;
use App\Domain\OrderItem;
use App\Repo\OrderRepo;
use App\Repo\ProductRepo;
use App\Service\OrderService;

Autoloader::register('App', __DIR__ . '/src');

$customer = (string)($_POST['customer'] ?? '');
$qty = $_POST['qty'] ?? []; // productId => qty

$errors = [];
$error = null;

try {
  $db = Db::conn();

  $productRepo = new ProductRepo($db);
  $orderRepo = new OrderRepo($db);
  $service = new OrderService($db, $orderRepo, $productRepo);

  $products = $productRepo->all();

  if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $c = trim($customer);
    if ($c === '') $errors['customer'] = 'A vevő neve kötelező.';

    $items = [];
    foreach ($products as $p) {
      $pid = (int)$p['id'];
      $raw = (string)($qty[$pid] ?? '0');
      $q = filter_var($raw, FILTER_VALIDATE_INT);
      if ($raw === '' || $q === false || $q < 0 || $q > 99) {
        $errors['qty_' . $pid] = 'Mennyiség 0–99.';
        continue;
      }
      if ((int)$q > 0) $items[] = new OrderItem($pid, (int)$q);
    }
    if (!$errors && !$items) $errors['form'] = 'Legalább 1 tétel mennyisége legyen > 0.';

    if (!$errors) {
      $id = $service->create(Order::createNew($c, $items));
      flash_set('Rendelés létrehozva (ID: ' . $id . ').');
      header('Location: ' . $_SERVER['PHP_SELF']);
      exit;
    }
  }

  $orders = $orderRepo->summaryList(20);
} catch (Throwable $e) {
  $error = $e->getMessage();
  $products = $products ?? [];
  $orders = [];
}

$flash = flash_get();
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session10 / Task02 – Transactional Service</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task02 – MySQLi + OOP: Tranzakció a Service rétegben</h1>
  </header>

  <div class="card notice">
    <p>Domain: <code>Order</code> + <code>OrderItem</code>, Repo: <code>OrderRepo</code>, Service: <code>OrderService</code> (begin/commit/rollback).</p>
  </div>

  <?php if ($error): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div><?php endif; ?>
  <?php if ($flash): ?><div class="card ok"><strong><?php echo h($flash); ?></strong></div><?php endif; ?>
  <?php if (isset($errors['form'])): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($errors['form']); ?></div><?php endif; ?>

  <div class="card">
    <h2>Új rendelés</h2>
    <form method="post" novalidate>
      <label for="customer">Vevő</label>
      <input id="customer" name="customer" type="text" value="<?php echo h($customer); ?>">
      <?php if (isset($errors['customer'])): ?><div class="field-error"><?php echo h($errors['customer']); ?></div><?php endif; ?>

      <h3>Termékek</h3>
      <table>
        <thead>
          <tr>
            <th>Név</th>
            <th>Ár</th>
            <th>Mennyiség</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($products as $p): $pid = (int)$p['id']; ?>
            <tr>
              <td><?php echo h((string)$p['name']); ?></td>
              <td><?php echo h(number_format((int)$p['price_ft'], 0, ',', ' ')); ?> Ft</td>
              <td>
                <input type="number" min="0" max="99" name="qty[<?php echo $pid; ?>]" value="<?php echo h((string)($qty[$pid] ?? '0')); ?>">
                <?php if (isset($errors['qty_' . $pid])): ?><div class="field-error"><?php echo h($errors['qty_' . $pid]); ?></div><?php endif; ?>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

      <button type="submit">Rendelés mentése</button>
    </form>
  </div>

  <div class="card">
    <h2>Rendelések összesítő</h2>
    <?php if (!$orders): ?><p class="small">Nincs rendelés.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Vevő</th>
            <th>Idő</th>
            <th>Darab</th>
            <th>Összeg</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($orders as $o): ?>
            <tr>
              <td><?php echo (int)$o['id']; ?></td>
              <td><?php echo h((string)$o['customer']); ?></td>
              <td class="small"><?php echo h((string)$o['created_at']); ?></td>
              <td><?php echo (int)$o['total_qty']; ?></td>
              <td><strong><?php echo h(number_format((int)$o['total_ft'], 0, ',', ' ')); ?> Ft</strong></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>