<?php

declare(strict_types=1);

// session_start(): elindítja a PHP session-t, így a $_SESSION tömbben perzisztens állapotot tárolhatunk a felhasználóhoz.
session_start();

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * Egyszerű "flash" üzenet kezelés sessionnel:
 * - flash_set(): üzenet eltárolása a következő oldalbetöltésig
 * - flash_get(): egyszeri kiolvasás (utána törlődik)
 * Megjegyzés: A flash_set() és flash_get() függvényeket a későbbi feladatok használják, ebben a feladatban még nem kerülnek alkalmazásra!
 */
function flash_set(string $key, string $message): void
{
  $_SESSION['_flash'][$key] = $message; // $_SESSION: session változók tárolása
}
function flash_get(string $key): ?string
{
  if (!isset($_SESSION['_flash'][$key])) return null;
  $msg = (string)$_SESSION['_flash'][$key];
  unset($_SESSION['_flash'][$key]); // unset(): törli a megadott kulcsot
  return $msg;
}
?>
<?php
$name = (string)($_POST['name'] ?? '');
$email = (string)($_POST['email'] ?? '');
$ageRaw = (string)($_POST['age'] ?? '');

$errors = []; // Hibák gyűjtése tömbbe: mezőnév => hibaüzenet
$ok = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $name = trim($name);
  $email = trim($email);

  if ($name === '') $errors['name'] = 'Kérem, adja meg a nevét.';
  if ($email === '') $errors['email'] = 'Kérem, adja meg az e-mail címét.';
  elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
    // filter_var(..., FILTER_VALIDATE_EMAIL): e-mail formátum ellenőrzése
    $errors['email'] = 'Az e-mail cím formátuma nem megfelelő.';
  }

  $age = filter_var($ageRaw, FILTER_VALIDATE_INT);
  if ($ageRaw === '') $errors['age'] = 'Kérem, adja meg az életkorát.';
  elseif ($age === false || $age < 0 || $age > 120) $errors['age'] = 'Az életkor csak 0 és 120 közötti egész lehet.';

  $ok = (count($errors) === 0);
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session03 / Task01 – Alap validáció</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task01 – Alap validáció és mezők visszatöltése</h1>
  </header>

  <div class="card notice">
    <p>A feladat célja: hibák mezőnkénti gyűjtése és a beküldött értékek visszatöltése a formba.</p>
  </div>

  <div class="card">
    <form method="post" novalidate>
      <div class="row">
        <div>
          <label for="name">Név</label>
          <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
          <?php if (isset($errors['name'])): ?>
            <div class="field-error"><?php echo h($errors['name']); ?></div>
          <?php endif; ?>
        </div>

        <div>
          <label for="age">Életkor</label>
          <input id="age" name="age" type="number" min="0" max="120" value="<?php echo h($ageRaw); ?>">
          <?php if (isset($errors['age'])): ?>
            <div class="field-error"><?php echo h($errors['age']); ?></div>
          <?php endif; ?>
        </div>
      </div>

      <label for="email">E-mail</label>
      <input id="email" name="email" type="text" value="<?php echo h($email); ?>">
      <?php if (isset($errors['email'])): ?>
        <div class="field-error"><?php echo h($errors['email']); ?></div>
      <?php endif; ?>

      <div style="margin-top:12px">
        <button type="submit">Beküldés</button>
      </div>
    </form>
  </div>

  <?php if ($ok): ?>
    <div class="card ok">
      <p><strong>Sikeres beküldés.</strong></p>
      <ul>
        <li>Név: <?php echo h($name); ?></li>
        <li>Életkor: <?php echo h($ageRaw); ?></li>
        <li>E-mail: <?php echo h($email); ?></li>
      </ul>
    </div>
  <?php elseif ($_SERVER['REQUEST_METHOD'] === 'POST'): ?>
    <div class="card err">
      <strong>Hiba:</strong> Kérem, javítsa a pirossal jelölt mezőket.
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>