<?php

declare(strict_types=1);

require_once __DIR__ . '/lib.php'; // require_once: egyszeri betöltés (dupla include ellen)

$priceRaw = (string)($_GET['price'] ?? '12345');
$qtyRaw   = (string)($_GET['qty'] ?? '2');

$price = filter_var($priceRaw, FILTER_VALIDATE_FLOAT);
$qty = filter_var($qtyRaw, FILTER_VALIDATE_INT);

if ($price === false) $price = 0.0;
if ($qty === false) $qty = 0;
$qty = clamp_int((int)$qty, 0, 999); // clamp_int(): tartományba kényszerítés

$total = (float)$price * (int)$qty;
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session05 / Task01 – Helper függvények</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task01 – Közös helper függvények külön fájlban</h1>
  </header>

  <div class="card notice">
    <p>Ebben a feladatban a HTML-escape és pénzformázás külön <code>lib.php</code> fájlban van.</p>
  </div>

  <div class="card">
    <form method="get" class="row" style="align-items:end">
      <div>
        <label for="price">Egységár (Ft)</label>
        <input id="price" name="price" type="text" value="<?php echo h($priceRaw); ?>">
      </div>
      <div>
        <label for="qty">Mennyiség</label>
        <input id="qty" name="qty" type="number" min="0" max="999" value="<?php echo h($qtyRaw); ?>">
      </div>
      <div><button type="submit">Számítás</button></div>
    </form>
  </div>

  <div class="card">
    <table>
      <tr>
        <th>Egységár</th>
        <td><?php echo h(money_huf((float)$price)); ?></td>
      </tr>
      <tr>
        <th>Mennyiség</th>
        <td><?php echo (int)$qty; ?></td>
      </tr>
      <tr>
        <th>Összesen</th>
        <td><strong><?php echo h(money_huf($total)); ?></strong></td>
      </tr>
    </table>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>