<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$aRaw = $_POST['a'] ?? '';
$bRaw = $_POST['b'] ?? '';
$error = '';
$res = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $a = array_map('trim', explode(',', (string)$aRaw)); // explode + array_map(trim)
  $b = array_map('trim', explode(',', (string)$bRaw));

  // üres elemek kidobása
  $a = array_values(array_filter($a, fn($x) => $x !== ''));
  $b = array_values(array_filter($b, fn($x) => $x !== ''));

  // array_merge(): összefűzés, array_unique(): egyediség
  $union = array_values(array_unique(array_merge($a, $b)));

  // array_intersect(): metszet (közös elemek)
  $intersect = array_values(array_intersect($a, $b));

  // array_diff(): különbség (A-ban van, B-ben nincs)
  $diffAB = array_values(array_diff($a, $b));

  $res = compact('a', 'b', 'union', 'intersect', 'diffAB');
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>09 – Halmazműveletek</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Halmazműveletek tömbökkel</h1>
  </header>

  <div class="card">
    <form method="post">
      <label for="a">Lista A (vesszővel elválasztva)</label>
      <input id="a" name="a" type="text" value="<?php echo h((string)$aRaw); ?>" placeholder="pl. alma, körte, banán">

      <label for="b">Lista B (vesszővel elválasztva)</label>
      <input id="b" name="b" type="text" value="<?php echo h((string)$bRaw); ?>" placeholder="pl. banán, citrom">

      <div style="margin-top:12px"><button type="submit">Számítás</button></div>
    </form>
  </div>

  <?php if ($res !== null): ?>
    <div class="card ok">
      <table>
        <tr>
          <th>A</th>
          <td><?php echo h(implode(', ', $res['a'])); ?></td>
        </tr>
        <tr>
          <th>B</th>
          <td><?php echo h(implode(', ', $res['b'])); ?></td>
        </tr>
        <tr>
          <th>Unió (A ∪ B)</th>
          <td><?php echo h(implode(', ', $res['union'])); ?></td>
        </tr>
        <tr>
          <th>Metszet (A ∩ B)</th>
          <td><?php echo h(implode(', ', $res['intersect'])); ?></td>
        </tr>
        <tr>
          <th>Különbség (A \ B)</th>
          <td><?php echo h(implode(', ', $res['diffAB'])); ?></td>
        </tr>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>