<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
  $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
  if (!is_dir($dir)) {
    mkdir($dir, 0777, true);
  }
  return $dir;
}
?>
<?php
$data = ensure_dir('data');
$file = $data . DIRECTORY_SEPARATOR . 'guestbook.txt';

$name = (string)($_POST['name'] ?? '');
$msg  = (string)($_POST['msg'] ?? '');
$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $name = trim($name);
  $msg = trim($msg);

  if ($name === '') $errors['name'] = 'Kérem, adja meg a nevét.';
  if ($msg === '') $errors['msg'] = 'Kérem, írjon üzenetet.';
  elseif (mb_strlen($msg, 'UTF-8') > 300) $errors['msg'] = 'Az üzenet legfeljebb 300 karakter lehet.';

  if (!$errors) {
    $safeName = str_replace('|', '/', $name);
    $safeMsg = str_replace(["\r", "\n", '|'], [' ', ' ', '/'], $msg);
    $line = date('Y-m-d H:i:s') . '|' . $safeName . '|' . $safeMsg . PHP_EOL;
    file_put_contents($file, $line, FILE_APPEND | LOCK_EX);
    header('Location: ' . $_SERVER['PHP_SELF']); // PRG
    exit;
  }
}

if (isset($_GET['clear'])) {
  if (is_file($file)) unlink($file);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$entries = [];
if (is_file($file)) {
  foreach (array_reverse(file($file, FILE_IGNORE_NEW_LINES)) as $r) {
    $p = explode('|', $r, 3);
    if (count($p) === 3) $entries[] = ['t' => $p[0], 'n' => $p[1], 'm' => $p[2]];
    if (count($entries) >= 20) break;
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session04 / Task02 – Vendégkönyv</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task02 – Vendégkönyv (szövegfájl)</h1>
  </header>

  <div class="card">
    <form method="post" novalidate>
      <div class="row">
        <div>
          <label for="name">Név</label>
          <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
          <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
        </div>
        <div>
          <label for="msg">Üzenet</label>
          <input id="msg" name="msg" type="text" value="<?php echo h($msg); ?>">
          <?php if (isset($errors['msg'])): ?><div class="field-error"><?php echo h($errors['msg']); ?></div><?php endif; ?>
        </div>
      </div>
      <div style="margin-top:12px"><button type="submit">Mentés</button></div>
    </form>
    <p class="small">Fájl: <code>data/guestbook.txt</code></p>
    <p><a href="?clear=1">Törlés</a></p>
  </div>

  <div class="card">
    <h2>Bejegyzések</h2>
    <?php if (!$entries): ?><p class="small">Nincs bejegyzés.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Idő</th>
            <th>Név</th>
            <th>Üzenet</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($entries as $e): ?>
            <tr>
              <td class="small"><?php echo h($e['t']); ?></td>
              <td><?php echo h($e['n']); ?></td>
              <td><?php echo h($e['m']); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>
  <footer class="small">Generated by PHP</footer>
</body>

</html>