<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$nameRaw = $_GET['name'] ?? ''; // A $_GET['name'] értékét olvassa ki, és ha nem létezik, akkor alapértelmezetten üres stringet ad vissza (null coalescing operátor).
$name = trim((string)$nameRaw);

$error = '';
$greeting = '';

if (isset($_GET['submit'])) {
  if ($name === '') {
    $error = 'Kérem, adja meg a nevét.';
  } else {
    $greeting = 'Hello, ' . $name . '!';
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>03 – GET köszönés</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>GET köszönés</h1>
  </header>

  <div class="card">
    <form method="get" action="">
      <label for="name">Név</label>
      <input id="name" name="name" type="text" value="<?php echo h($name); ?>" placeholder="Pl. Kovács Anna">
      <div style="margin-top:12px">
        <button name="submit" value="1" type="submit">Küldés</button>
      </div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($greeting !== ''): ?>
    <div class="card ok"><?php echo h($greeting); ?></div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>