<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$nRaw = $_POST['n'] ?? '5';
$mRaw = $_POST['m'] ?? '5';
$error = '';
$grid = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $n = filter_var($nRaw, FILTER_VALIDATE_INT);
  $m = filter_var($mRaw, FILTER_VALIDATE_INT);

  if ($n === false || $m === false || $n < 1 || $m < 1 || $n > 30 || $m > 30) {
    $error = 'Kérem, 1 és 30 közötti egész számokat adjon meg.';
  } else {
    $grid = [];

    // Kétdimenziós tömb felépítése (sorok -> oszlopok)
    for ($i = 1; $i <= $n; $i++) {
      $row = [];
      for ($j = 1; $j <= $m; $j++) {
        $row[] = $i * $j;
      }
      $grid[] = $row;
    }
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>10 – Szorzótábla rács</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Szorzótábla rács (kétdimenziós tömb)</h1>
  </header>

  <div class="card">
    <form method="post">
      <label for="n">Sorok száma (N)</label>
      <input id="n" name="n" type="number" min="1" max="30" value="<?php echo h((string)$nRaw); ?>">

      <label for="m">Oszlopok száma (M)</label>
      <input id="m" name="m" type="number" min="1" max="30" value="<?php echo h((string)$mRaw); ?>">

      <div style="margin-top:12px"><button type="submit">Generálás</button></div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($grid !== null): ?>
    <div class="card ok">
      <table>
        <thead>
          <tr>
            <th>×</th>
            <?php for ($j = 1; $j <= count($grid[0]); $j++): ?>
              <th><?php echo (int)$j; ?></th>
            <?php endfor; ?>
          </tr>
        </thead>
        <tbody>
          <?php for ($i = 0; $i < count($grid); $i++): ?>
            <tr>
              <th><?php echo (int)($i + 1); ?></th>
              <?php foreach ($grid[$i] as $cell): ?>
                <td><?php echo (int)$cell; ?></td>
              <?php endforeach; ?>
            </tr>
          <?php endfor; ?>
        </tbody>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>