<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Event\EventDispatcher;
use App\Event\NoteCreated;
use App\Log\FileLogger;
use App\Repo\JsonNoteRepository;
use App\Service\NoteService;

Autoloader::register('App', __DIR__ . '/src');

$dataDir = __DIR__ . '/data';
if (!is_dir($dataDir)) mkdir($dataDir, 0777, true);

$notesFile = $dataDir . '/notes.json';
$logFile = $dataDir . '/events.log';
$counterFile = $dataDir . '/counter.txt';

$dispatcher = new EventDispatcher();
$logger = new FileLogger($logFile);

// Listener #1: logolás
$dispatcher->addListener(NoteCreated::class, function (NoteCreated $e) use ($logger): void {
  $logger->log('INFO', 'NoteCreated', ['id' => $e->id]);
});

// Listener #2: számláló növelése (egyszerű statisztika)
$dispatcher->addListener(NoteCreated::class, function (NoteCreated $e) use ($counterFile): void {
  $n = is_file($counterFile) ? (int)trim((string)file_get_contents($counterFile)) : 0;
  file_put_contents($counterFile, (string)($n + 1), LOCK_EX);
});

$service = new NoteService(new JsonNoteRepository($notesFile), $dispatcher);

$text = (string)($_POST['text'] ?? '');
$errors = [];
$flash = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  try {
    $service->add($text);
    header('Location: ' . $_SERVER['PHP_SELF'] . '?ok=1');
    exit; // PRG
  } catch (Throwable $e) {
    $errors['text'] = $e->getMessage();
  }
}

if (isset($_GET['clear'])) {
  foreach ([$notesFile, $logFile, $counterFile] as $f) if (is_file($f)) unlink($f);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$notes = $service->all();
$count = is_file($counterFile) ? (int)trim((string)file_get_contents($counterFile)) : 0;
$lines = is_file($logFile) ? array_slice(array_reverse(file($logFile, FILE_IGNORE_NEW_LINES)), 0, 10) : [];
$flash = isset($_GET['ok']) ? 'Jegyzet mentve (események lefutottak).' : null;
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session08 / Task03 – Observer</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task03 – Observer/Event Dispatcher (NoteCreated)</h1>
  </header>

  <div class="card notice">
    <p>Eseménykibocsátás + listener-ek: logolás és számláló növelése. <a href="?clear=1">Adatok törlése</a></p>
  </div>

  <?php if ($flash): ?><div class="card ok"><strong><?php echo h($flash); ?></strong></div><?php endif; ?>

  <div class="card">
    <form method="post" novalidate>
      <label for="text">Új jegyzet (max 200)</label>
      <input id="text" name="text" type="text" value="<?php echo h($text); ?>">
      <?php if (isset($errors['text'])): ?><div class="field-error"><?php echo h($errors['text']); ?></div><?php endif; ?>
      <div style="margin-top:12px"><button type="submit">Mentés</button></div>
    </form>
    <p class="small">Események összesen: <strong><?php echo (int)$count; ?></strong></p>
  </div>

  <div class="card">
    <h2>Jegyzetek (<?php echo (int)count($notes); ?>)</h2>
    <?php if (!$notes): ?><p class="small">Nincs jegyzet.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Idő</th>
            <th>ID</th>
            <th>Szöveg</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach (array_reverse($notes) as $n): ?>
            <tr>
              <td class="small"><?php echo h($n->createdAt()); ?></td>
              <td class="small"><code><?php echo h($n->id()); ?></code></td>
              <td><?php echo h($n->text()); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <div class="card">
    <h2>Utolsó 10 esemény-log sor</h2>
    <?php if (!$lines): ?><p class="small">Üres.</p>
    <?php else: ?><ul><?php foreach ($lines as $l): ?><li class="small"><code><?php echo h($l); ?></code></li><?php endforeach; ?></ul><?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>