<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Pricing\JsonCatalogPriceProvider;
use App\Pricing\DiscountDecorator;
use App\Pricing\CacheDecorator;

Autoloader::register('App', __DIR__ . '/src');

$dataDir = __DIR__ . '/data';
$catalogFile = $dataDir . '/catalog.json';
$cacheFile = $dataDir . '/cache.json';

$productId = (string)($_POST['product'] ?? 'p1');
$discountRaw = (string)($_POST['discount'] ?? '10');
$useCache = isset($_POST['use_cache']);
$errors = [];
$out = null;
$stats = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $disc = filter_var($discountRaw, FILTER_VALIDATE_FLOAT);
  if ($discountRaw === '' || $disc === false || $disc < 0 || $disc > 90) $errors['discount'] = 'Kérem, 0–90 közötti százalékot adjon meg.';

  if (!$errors) {
    $base = new JsonCatalogPriceProvider($catalogFile);
    $provider = new DiscountDecorator($base, ((float)$disc) / 100.0);

    if ($useCache) {
      $cached = new CacheDecorator($provider, $cacheFile);
      $provider = $cached;
    }

    try {
      $price = $provider->getPriceFt($productId);
      $out = ['provider' => $provider->name(), 'price' => $price];
      if (isset($cached)) $stats = $cached->stats();
    } catch (Throwable $e) {
      $errors['product'] = $e->getMessage();
    }
  }
}

if (isset($_GET['clear'])) {
  if (is_file($cacheFile)) unlink($cacheFile);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$catalog = json_decode((string)file_get_contents($catalogFile), true);
if (!is_array($catalog)) $catalog = [];
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session08 / Task04 – Decorator</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task04 – Decorator: kedvezmény + cache</h1>
  </header>

  <div class="card notice">
    <p>A <code>PriceProvider</code> köré dekorátorok tekerhetők: kedvezmény számítás és opcionális cache. <a href="?clear=1">Cache törlése</a></p>
  </div>

  <div class="card">
    <form method="post" novalidate class="row" style="align-items:end">
      <div>
        <label for="product">Termék</label>
        <select id="product" name="product">
          <?php foreach ($catalog as $p): ?>
            <option value="<?php echo h((string)$p['id']); ?>" <?php echo $productId === (string)$p['id'] ? 'selected' : ''; ?>>
              <?php echo h((string)$p['name']); ?> (<?php echo (int)$p['price_ft']; ?> Ft)
            </option>
          <?php endforeach; ?>
        </select>
        <?php if (isset($errors['product'])): ?><div class="field-error"><?php echo h($errors['product']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="discount">Kedvezmény (%)</label>
        <input id="discount" name="discount" type="text" value="<?php echo h($discountRaw); ?>">
        <?php if (isset($errors['discount'])): ?><div class="field-error"><?php echo h($errors['discount']); ?></div><?php endif; ?>
      </div>
      <div>
        <label><input type="checkbox" name="use_cache" <?php echo $useCache ? 'checked' : ''; ?>> Cache használata</label>
        <div class="small">Cache fájl: <code>data/cache.json</code></div>
      </div>
      <div><button type="submit">Ár lekérése</button></div>
    </form>
  </div>

  <?php if ($out): ?>
    <div class="card ok">
      <h2>Eredmény</h2>
      <table>
        <tr>
          <th>Provider lánc</th>
          <td><?php echo h($out['provider']); ?></td>
        </tr>
        <tr>
          <th>Ár</th>
          <td><strong><?php echo h(number_format((int)$out['price'], 0, ',', ' ')); ?> Ft</strong></td>
        </tr>
        <?php if ($stats): ?>
          <tr>
            <th>Cache stat</th>
            <td>hit: <?php echo (int)$stats['hits']; ?>, miss: <?php echo (int)$stats['misses']; ?></td>
          </tr>
        <?php endif; ?>
      </table>
      <p class="small">Tipp: kérje le ugyanazt a terméket többször bekapcsolt cache-sel, és nézze a hit/miss értékeket.</p>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>