<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
  $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
  if (!is_dir($dir)) {
    mkdir($dir, 0777, true);
  }
  return $dir;
}
?>
<?php
$data = ensure_dir('data');
$file = $data . DIRECTORY_SEPARATOR . 'grades.csv';

function read_csv(string $file): array
{
  if (!is_file($file)) return [];
  $rows = [];
  $fh = fopen($file, 'r'); // fopen(): fájl megnyitása
  if ($fh === false) return [];
  while (($row = fgetcsv($fh, 0, ';')) !== false) { // fgetcsv(): CSV sor beolvasása
    if (count($row) === 3) $rows[] = ['name' => $row[0], 'neptun' => $row[1], 'grade' => $row[2]];
  }
  fclose($fh);
  return $rows;
}
function append_csv(string $file, array $row): void
{
  $fh = fopen($file, 'a');
  if ($fh === false) return;
  flock($fh, LOCK_EX); // flock(): fájl zárolás írás közben
  fputcsv($fh, [$row['name'], $row['neptun'], $row['grade']], ';'); // fputcsv(): CSV sor kiírása
  flock($fh, LOCK_UN);
  fclose($fh);
}

$name = (string)($_POST['name'] ?? '');
$neptun = (string)($_POST['neptun'] ?? '');
$gradeRaw = (string)($_POST['grade'] ?? '');
$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $name = trim($name);
  $neptun = strtoupper(trim($neptun));
  $grade = filter_var($gradeRaw, FILTER_VALIDATE_INT);

  if ($name === '') $errors['name'] = 'Kérem, adja meg a nevet.';
  if ($neptun === '' || !preg_match('/^[A-Z0-9]{6}$/', $neptun)) $errors['neptun'] = 'Hibás Neptun (6 karakter).';
  if ($gradeRaw === '' || $grade === false || $grade < 1 || $grade > 5) $errors['grade'] = 'A jegy 1–5 közötti egész legyen.';

  if (!$errors) {
    append_csv($file, ['name' => $name, 'neptun' => $neptun, 'grade' => (string)$grade]);
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  }
}

if (isset($_GET['clear'])) {
  if (is_file($file)) unlink($file);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$rows = read_csv($file);
$grades = array_map(fn($r) => (int)$r['grade'], $rows);
$avg = $grades ? array_sum($grades) / count($grades) : null;
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session04 / Task05 – CSV</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task05 – Jegyek mentése CSV-be</h1>
  </header>

  <div class="card">
    <form method="post" novalidate>
      <div class="row">
        <div>
          <label for="name">Név</label>
          <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
          <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
        </div>
        <div>
          <label for="neptun">Neptun</label>
          <input id="neptun" name="neptun" type="text" value="<?php echo h($neptun); ?>">
          <?php if (isset($errors['neptun'])): ?><div class="field-error"><?php echo h($errors['neptun']); ?></div><?php endif; ?>
        </div>
      </div>
      <label for="grade">Jegy (1–5)</label>
      <input id="grade" name="grade" type="number" min="1" max="5" value="<?php echo h($gradeRaw); ?>">
      <?php if (isset($errors['grade'])): ?><div class="field-error"><?php echo h($errors['grade']); ?></div><?php endif; ?>
      <div style="margin-top:12px"><button type="submit">Hozzáadás</button></div>
    </form>
    <p class="small">Fájl: <code>data/grades.csv</code> (elválasztó: ; ) · <a href="?clear=1">Törlés</a></p>
  </div>

  <div class="card">
    <h2>Lista (<?php echo (int)count($rows); ?> sor)</h2>
    <?php if (!$rows): ?><p class="small">Nincs adat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Név</th>
            <th>Neptun</th>
            <th>Jegy</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach (array_reverse($rows) as $r): ?>
            <tr>
              <td><?php echo h($r['name']); ?></td>
              <td><?php echo h($r['neptun']); ?></td>
              <td><?php echo h((string)$r['grade']); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <p><strong>Átlag:</strong> <?php echo h(number_format((float)$avg, 2, ',', ' ')); ?></p>
    <?php endif; ?>
  </div>
  <footer class="small">Generated by PHP</footer>
</body>

</html>