<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Service\CheckoutService;
use App\Shipping\FlatRateStrategy;
use App\Shipping\DistanceBasedStrategy;

Autoloader::register('App', __DIR__ . '/src');

$strategyId = (string)($_POST['strategy'] ?? 'flat');
$weightRaw = (string)($_POST['weight'] ?? '2.5');
$distRaw = (string)($_POST['distance'] ?? '15');
$subtotalRaw = (string)($_POST['subtotal'] ?? '12000');

$errors = [];
$out = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $w = filter_var($weightRaw, FILTER_VALIDATE_FLOAT);
  $d = filter_var($distRaw, FILTER_VALIDATE_FLOAT);
  $s = filter_var($subtotalRaw, FILTER_VALIDATE_INT);

  if ($weightRaw === '' || $w === false || $w < 0) $errors['weight'] = 'A súly legyen 0 vagy pozitív szám.';
  if ($distRaw === '' || $d === false || $d < 0) $errors['distance'] = 'A távolság legyen 0 vagy pozitív szám.';
  if ($subtotalRaw === '' || $s === false || $s < 0) $errors['subtotal'] = 'A részösszeg legyen 0 vagy pozitív egész.';
  if (!in_array($strategyId, ['flat', 'dist'], true)) $errors['strategy'] = 'Ismeretlen stratégia.';

  if (!$errors) {
    $strategy = $strategyId === 'flat'
      ? new FlatRateStrategy(1990)
      : new DistanceBasedStrategy(990, 35, 0.08);

    $service = new CheckoutService($strategy);
    $res = $service->calculate((float)$w, (float)$d, (int)$s);

    $out = [
      'strategy' => $strategy->name(),
      'shipping' => $res['shippingFt'],
      'total' => $res['totalFt'],
    ];
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session08 / Task02 – Strategy</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task02 – Strategy minta: szállítási díj számítás</h1>
  </header>

  <div class="card notice">
    <p>A szállítási díj algoritmusa cserélhető: <code>ShippingStrategy</code> interface + több implementáció.</p>
  </div>

  <div class="card">
    <form method="post" novalidate class="row" style="align-items:end">
      <div>
        <label for="strategy">Stratégia</label>
        <select id="strategy" name="strategy">
          <option value="flat" <?php echo $strategyId === 'flat' ? 'selected' : ''; ?>>Fix díj</option>
          <option value="dist" <?php echo $strategyId === 'dist' ? 'selected' : ''; ?>>Távolság alapú</option>
        </select>
        <?php if (isset($errors['strategy'])): ?><div class="field-error"><?php echo h($errors['strategy']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="weight">Súly (kg)</label>
        <input id="weight" name="weight" type="text" value="<?php echo h($weightRaw); ?>">
        <?php if (isset($errors['weight'])): ?><div class="field-error"><?php echo h($errors['weight']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="distance">Távolság (km)</label>
        <input id="distance" name="distance" type="text" value="<?php echo h($distRaw); ?>">
        <?php if (isset($errors['distance'])): ?><div class="field-error"><?php echo h($errors['distance']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="subtotal">Részösszeg (Ft)</label>
        <input id="subtotal" name="subtotal" type="number" min="0" value="<?php echo h($subtotalRaw); ?>">
        <?php if (isset($errors['subtotal'])): ?><div class="field-error"><?php echo h($errors['subtotal']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Számítás</button></div>
    </form>
  </div>

  <?php if ($out): ?>
    <div class="card ok">
      <h2>Eredmény</h2>
      <table>
        <tr>
          <th>Használt stratégia</th>
          <td><?php echo h($out['strategy']); ?></td>
        </tr>
        <tr>
          <th>Szállítás</th>
          <td><?php echo h(number_format((int)$out['shipping'], 0, ',', ' ')); ?> Ft</td>
        </tr>
        <tr>
          <th>Végösszeg</th>
          <td><strong><?php echo h(number_format((int)$out['total'], 0, ',', ' ')); ?> Ft</strong></td>
        </tr>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>