<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$students = [
  [
    'name' => 'Kiss Anna',
    'neptun' => 'AAA111',
    'grades' => [5, 4, 5, 3],
  ],
  [
    'name' => 'Nagy Béla',
    'neptun' => 'BBB222',
    'grades' => [2, 3, 3, 4],
  ],
  [
    'name' => 'Szabó Csilla',
    'neptun' => 'CCC333',
    'grades' => [5, 5, 5],
  ],
];

function avg(array $nums): float
{
  // count(): elemszám, array_sum(): összeg
  return count($nums) ? (array_sum($nums) / count($nums)) : 0.0;
}

function nf(float $v): string
{
  return number_format($v, 2, ',', ' ');
}

$rows = [];
$classAvgs = [];

foreach ($students as $s) {
  $a = avg($s['grades']);
  $rows[] = [
    'name' => $s['name'],
    'neptun' => $s['neptun'],
    'grades' => $s['grades'],
    'avg' => $a
  ];
  $classAvgs[] = $a;
}

$groupAvg = count($classAvgs) ? array_sum($classAvgs) / count($classAvgs) : 0.0;
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>06 – Jegyzetfüzet</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Jegyek kezelése (többdimenziós tömb)</h1>
  </header>

  <div class="card">
    <table>
      <thead>
        <tr>
          <th>Hallgató</th>
          <th>Neptun</th>
          <th>Jegyek</th>
          <th>Átlag</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($rows as $r): ?>
          <tr>
            <td><?php echo h($r['name']); ?></td>
            <td><?php echo h($r['neptun']); ?></td>
            <td><?php echo h(implode(', ', array_map('strval', $r['grades']))); ?></td>
            <td><?php echo h(nf((float)$r['avg'])); ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="3">Csoportátlag (hallgatói átlagok átlaga)</th>
          <th><?php echo h(nf((float)$groupAvg)); ?></th>
        </tr>
      </tfoot>
    </table>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>