<?php
declare(strict_types=1);

// session_start(): elindítja a PHP session-t, így a $_SESSION tömbben perzisztens állapotot tárolhatunk a felhasználóhoz.
session_start();

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string {
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * Egyszerű "flash" üzenet kezelés sessionnel:
 * - flash_set(): üzenet eltárolása a következő oldalbetöltésig
 * - flash_get(): egyszeri kiolvasás (utána törlődik)
 */
function flash_set(string $key, string $message): void {
    $_SESSION['_flash'][$key] = $message; // $_SESSION: session változók tárolása
}
function flash_get(string $key): ?string {
    if (!isset($_SESSION['_flash'][$key])) return null;
    $msg = (string)$_SESSION['_flash'][$key];
    unset($_SESSION['_flash'][$key]); // unset(): törli a megadott kulcsot
    return $msg;
}
?>
<?php
// CSRF token kezelés sessionben (demó):
// - token generálás random_bytes() segítségével
// - összehasonlítás POST-ban
function csrf_token(): string {
    if (!isset($_SESSION['_csrf'])) {
        $_SESSION['_csrf'] = bin2hex(random_bytes(16)); // random_bytes(): kriptográfiailag biztonságos random
    }
    return (string)$_SESSION['_csrf'];
}
function csrf_check(?string $token): bool {
    if (!isset($_SESSION['_csrf'])) return false;
    // hash_equals(): biztonságos összehasonlítás
    return is_string($token) && hash_equals((string)$_SESSION['_csrf'], $token);
}
function csrf_rotate(): void {
    $_SESSION['_csrf'] = bin2hex(random_bytes(16));
}

$subject = (string)($_POST['subject'] ?? '');
$message = (string)($_POST['message'] ?? '');
$errors = [];
$success = flash_get('success');
$errorMsg = flash_get('error');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $token = (string)($_POST['_csrf'] ?? '');

    if (!csrf_check($token)) {
        flash_set('error', 'Biztonsági hiba: érvénytelen CSRF token (a kérés elutasítva).');
        header('Location: ' . $_SERVER['PHP_SELF']);
        exit;
    }

    $subject = trim($subject);
    $message = trim($message);

    if ($subject === '') $errors['subject'] = 'Kérem, adja meg a tárgyat.';
    if ($message === '') $errors['message'] = 'Kérem, adja meg az üzenetet.';
    elseif (mb_strlen($message, 'UTF-8') < 10) $errors['message'] = 'Az üzenet legyen legalább 10 karakter hosszú.';

    if (count($errors) === 0) {
        $_SESSION['task10_messages'][] = [
            'subject' => $subject,
            'message' => $message,
            'at' => date('Y-m-d H:i:s'),
        ];
        // Token rotálása sikeres POST után (jó gyakorlat)
        csrf_rotate();
        flash_set('success', 'Az üzenet rögzítésre került (session).');
        header('Location: ' . $_SERVER['PHP_SELF']);
        exit;
    }
}

$list = $_SESSION['task10_messages'] ?? [];
?>
<!doctype html>
<html lang="hu">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session03 / Task10 – CSRF védelem</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
<header><h1>Task10 – CSRF védelemmel ellátott űrlap (session)</h1></header>

<?php if ($success): ?><div class="card ok"><?php echo h($success); ?></div><?php endif; ?>
<?php if ($errorMsg): ?><div class="card err"><?php echo h($errorMsg); ?></div><?php endif; ?>

<div class="card">
  <form method="post" novalidate>
    <input type="hidden" name="_csrf" value="<?php echo h(csrf_token()); ?>">

    <label for="subject">Tárgy</label>
    <input id="subject" name="subject" type="text" value="<?php echo h($subject); ?>">
    <?php if (isset($errors['subject'])): ?><div class="field-error"><?php echo h($errors['subject']); ?></div><?php endif; ?>

    <label for="message">Üzenet</label>
    <textarea id="message" name="message" rows="5"><?php echo h($message); ?></textarea>
    <?php if (isset($errors['message'])): ?><div class="field-error"><?php echo h($errors['message']); ?></div><?php endif; ?>

    <div style="margin-top:12px"><button type="submit">Küldés</button></div>
  </form>

  <p class="small">Megjegyzés: a CSRF token a sessionben van tárolva, és minden sikeres beküldés után újragenerálódik.</p>
</div>

<div class="card">
  <h2>Mentett üzenetek (session)</h2>
  <?php if (count($list) === 0): ?>
    <p class="small">Nincs elem.</p>
  <?php else: ?>
    <table>
      <thead><tr><th>#</th><th>Időpont</th><th>Tárgy</th><th>Üzenet</th></tr></thead>
      <tbody>
      <?php foreach ($list as $i => $m): ?>
        <tr>
          <td><?php echo (int)($i+1); ?></td>
          <td><?php echo h($m['at']); ?></td>
          <td><?php echo h($m['subject']); ?></td>
          <td><?php echo h($m['message']); ?></td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  <?php endif; ?>
</div>

<footer class="small">Generated by PHP</footer>
</body>
</html>
