<?php

declare(strict_types=1);
require_once __DIR__ . '/lib.php';
require_once __DIR__ . '/logger.php';

$title = 'Task08 – Logger modul (INFO/WARN/ERROR)';

$dataDir = ensure_data_dir();
$logFile = $dataDir . DIRECTORY_SEPARATOR . 'app.log';

$level = (string)($_POST['level'] ?? 'info');
$message = (string)($_POST['message'] ?? '');
$errors = [];

$levels = ['info' => 'INFO', 'warn' => 'WARN', 'error' => 'ERROR'];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  if (!isset($levels[$level])) $errors['level'] = 'Kérem, válasszon szintet.';
  $message = trim($message);
  if ($message === '') $errors['message'] = 'Kérem, adjon meg üzenetet.';
  if (!$errors) {
    logger_write($logFile, $level, $message, ['ip' => ($_SERVER['REMOTE_ADDR'] ?? 'unknown')]);
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  }
}
if (isset($_GET['clear'])) {
  if (is_file($logFile)) unlink($logFile);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$lines = is_file($logFile) ? array_slice(array_reverse(file($logFile, FILE_IGNORE_NEW_LINES)), 0, 30) : [];
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo h($title); ?></title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1><?php echo h($title); ?></h1>
  </header>

  <div class="card notice">
    <p>A naplóírás a <code>logger.php</code> modulban van (egységes formátum + FILE_APPEND + LOCK_EX).</p>
  </div>

  <div class="card">
    <form method="post" novalidate class="row" style="align-items:end">
      <div>
        <label for="level">Szint</label>
        <select id="level" name="level">
          <?php foreach ($levels as $k => $lbl): ?>
            <option value="<?php echo h($k); ?>" <?php echo $level === $k ? 'selected' : ''; ?>><?php echo h($lbl); ?></option>
          <?php endforeach; ?>
        </select>
        <?php if (isset($errors['level'])): ?><div class="field-error"><?php echo h($errors['level']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="message">Üzenet</label>
        <input id="message" name="message" type="text" value="<?php echo h($message); ?>">
        <?php if (isset($errors['message'])): ?><div class="field-error"><?php echo h($errors['message']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Logol</button></div>
    </form>
    <p class="small">Fájl: <code>data/app.log</code> · <a href="?clear=1">Törlés</a></p>
  </div>

  <div class="card">
    <h2>Utolsó 30 sor</h2>
    <?php if (!$lines): ?><p class="small">Üres log.</p>
    <?php else: ?>
      <ul>
        <?php foreach ($lines as $l): ?><li class="small"><code><?php echo h($l); ?></code></li><?php endforeach; ?>
      </ul>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>