<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Domain\Student;
use App\Repo\StudentRepository;

Autoloader::register('App', __DIR__ . '/src');

$dataDir = __DIR__ . '/data';
if (!is_dir($dataDir)) mkdir($dataDir, 0777, true);
$file = $dataDir . '/students.json';

$repo = new StudentRepository($file);

$name = (string)($_POST['name'] ?? '');
$neptun = (string)($_POST['neptun'] ?? '');
$pointsRaw = (string)($_POST['points'] ?? '0');
$errors = [];
$flash = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $p = filter_var($pointsRaw, FILTER_VALIDATE_INT);
  if (trim($name) === '') $errors['name'] = 'A név kötelező.';
  if (!preg_match('/^[A-Za-z0-9]{6}$/', trim($neptun))) $errors['neptun'] = 'A Neptun 6 alfanumerikus karakter.';
  if ($pointsRaw === '' || $p === false || $p < 0 || $p > 100) $errors['points'] = 'A pont legyen 0–100 közötti egész.';
  if (!$errors) {
    $repo->add(Student::create($name, $neptun, (int)$p));
    header('Location: ' . $_SERVER['PHP_SELF'] . '?ok=1');
    exit; // PRG
  }
}

if (isset($_GET['clear'])) {
  if (is_file($file)) unlink($file);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$flash = isset($_GET['ok']) ? 'Hallgató hozzáadva.' : null;
$students = $repo->all();
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session08 / Task05 – Template Method + Factory</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task05 – Template Method + Factory (riport generálás)</h1>
  </header>

  <div class="card notice">
    <p>Riport generálás: <code>ReportGenerator</code> (Template Method) + <code>ReportFactory</code> (Factory). <a href="?clear=1">Adatok törlése</a></p>
  </div>

  <?php if ($flash): ?><div class="card ok"><strong><?php echo h($flash); ?></strong></div><?php endif; ?>

  <div class="card">
    <h2>Új hallgató</h2>
    <form method="post" class="row" style="align-items:end" novalidate>
      <div>
        <label for="name">Név</label>
        <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
        <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="neptun">Neptun</label>
        <input id="neptun" name="neptun" type="text" value="<?php echo h($neptun); ?>">
        <?php if (isset($errors['neptun'])): ?><div class="field-error"><?php echo h($errors['neptun']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="points">Pont (0–100)</label>
        <input id="points" name="points" type="number" min="0" max="100" value="<?php echo h($pointsRaw); ?>">
        <?php if (isset($errors['points'])): ?><div class="field-error"><?php echo h($errors['points']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Hozzáadás</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Lista (<?php echo (int)count($students); ?>)</h2>
    <?php if (!$students): ?><p class="small">Nincs adat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Név</th>
            <th>Neptun</th>
            <th>Pont</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($students as $s): ?>
            <tr>
              <td><?php echo h($s->name()); ?></td>
              <td><code><?php echo h($s->neptun()); ?></code></td>
              <td><?php echo (int)$s->points(); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <div class="card">
    <h2>Riport letöltés</h2>
    <p>
      <a href="download.php?format=csv">CSV letöltés</a> ·
      <a href="download.php?format=html">HTML letöltés</a>
    </p>
    <p class="small">A letöltést a <code>download.php</code> végzi, a formátumtól függően a Factory más generátort ad.</p>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>