<?php

declare(strict_types=1);

// session_start(): elindítja a PHP session-t, így a $_SESSION tömbben perzisztens állapotot tárolhatunk a felhasználóhoz.
session_start();

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * Egyszerű "flash" üzenet kezelés sessionnel:
 * - flash_set(): üzenet eltárolása a következő oldalbetöltésig
 * - flash_get(): egyszeri kiolvasás (utána törlődik)
 */
function flash_set(string $key, string $message): void
{
  $_SESSION['_flash'][$key] = $message; // $_SESSION: session változók tárolása
}
function flash_get(string $key): ?string
{
  if (!isset($_SESSION['_flash'][$key])) return null;
  $msg = (string)$_SESSION['_flash'][$key];
  unset($_SESSION['_flash'][$key]); // unset(): törli a megadott kulcsot
  return $msg;
}
?>
<?php
// $_SESSION-ben számláljuk, hányszor nyitotta meg a felhasználó ezt az oldalt.
$_SESSION['task08_visits'] = ($_SESSION['task08_visits'] ?? 0) + 1;

$now = date('Y-m-d H:i:s');
$last = $_SESSION['task08_last'] ?? null;
$_SESSION['task08_last'] = $now;

if (isset($_GET['reset'])) {
  unset($_SESSION['task08_visits'], $_SESSION['task08_last']);
  flash_set('success', 'A számláló nullázva lett.');
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$success = flash_get('success');
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session03 / Task08 – Látogatásszámláló</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task08 – Látogatásszámláló és utolsó látogatás (session)</h1>
  </header>

  <?php if ($success): ?><div class="card ok"><?php echo h($success); ?></div><?php endif; ?>

  <div class="card">
    <p><strong>Megnyitások száma ebben a sessionben:</strong> <?php echo (int)$_SESSION['task08_visits']; ?></p>
    <p><strong>Aktuális idő:</strong> <?php echo h($now); ?></p>
    <p><strong>Előző látogatás időpontja:</strong> <?php echo $last ? h((string)$last) : '<span class="small">Nincs (első látogatás)</span>'; ?></p>
    <p><a href="?reset=1">Nullázás</a></p>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>