<?php

declare(strict_types=1);
/** @var string $title */
/** @var string $content */
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo h($title); ?></title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1><?php echo h($title); ?></h1>
  </header>
  <nav class="small">
    <a href="?action=list">Lista</a>
    <a href="?action=create">Új</a>
  </nav>
  <?php if (!empty($_SESSION['flash'])): ?>
    <div class="card ok"><strong><?php echo h((string)$_SESSION['flash']); ?></strong></div>
    <?php unset($_SESSION['flash']); ?>
  <?php endif; ?>
  <?php echo $content; ?>
  <footer class="small">Generated by PHP</footer>
</body>

</html>