<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$textRaw = $_POST['text'] ?? '';
$text = (string)$textRaw;

$stats = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $len = mb_strlen($text, 'UTF-8'); // Az mb_strlen() UTF-8 kompatibilisen számolja meg a sztring karaktereinek számát (nem bájtok számát).

  $spaces = 0;
  $vowels = 0;

  $vowelSet = 'aeiouáéíóöőúüűAEIOUÁÉÍÓÖŐÚÜŰ';

  // iterate by UTF-8 characters
  for ($i = 0; $i < $len; $i++) {
    $ch = mb_substr($text, $i, 1, 'UTF-8'); // Az mb_substr() UTF-8 kompatibilisen kivágja a szöveg egy karakterét a megadott pozícióról.
    if ($ch === ' ') $spaces++;
    if (mb_strpos($vowelSet, $ch, 0, 'UTF-8') !== false) $vowels++; // Az mb_strpos() UTF-8 kompatibilisen megkeresi egy karakter pozícióját egy sztringben (itt: magánhangzó-e).
  }

  // reverse (UTF-8 safe)
  $chars = [];
  for ($i = 0; $i < $len; $i++) {
    $chars[] = mb_substr($text, $i, 1, 'UTF-8');
  }
  $reversed = implode('', array_reverse($chars)); // Az array_reverse() megfordítja a karakterek tömbjét, az implode() pedig újra összefűzi őket egy sztringgé.

  $stats = [
    'len' => $len,
    'spaces' => $spaces,
    'vowels' => $vowels,
    'reversed' => $reversed
  ];
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>08 – Karakterstatisztika</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Karakterstatisztika</h1>
  </header>

  <div class="card">
    <form method="post" action="">
      <label for="text">Szöveg</label>
      <textarea id="text" name="text" rows="5" style="width:100%"><?php echo h($text); ?></textarea>
      <div style="margin-top:12px">
        <button type="submit">Elemzés</button>
      </div>
    </form>
  </div>

  <?php if ($stats !== null): ?>
    <div class="card ok">
      <table>
        <tr>
          <th>Összes karakter</th>
          <td><?php echo (int)$stats['len']; ?></td>
        </tr>
        <tr>
          <th>Szóközök száma</th>
          <td><?php echo (int)$stats['spaces']; ?></td>
        </tr>
        <tr>
          <th>Magánhangzók száma</th>
          <td><?php echo (int)$stats['vowels']; ?></td>
        </tr>
        <tr>
          <th>Visszafelé</th>
          <td><?php echo h($stats['reversed']); ?></td>
        </tr>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>