<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
  $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
  if (!is_dir($dir)) {
    mkdir($dir, 0777, true);
  }
  return $dir;
}
?>
<?php
$uploads = ensure_dir('uploads');

$errors = [];
$allowed = ['image/jpeg' => 'jpg', 'image/png' => 'png', 'image/gif' => 'gif'];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  if (!isset($_FILES['file'])) $errors['file'] = 'Kérem, válasszon fájlt.';
  else {
    $f = $_FILES['file'];
    if ($f['error'] !== UPLOAD_ERR_OK) $errors['file'] = 'Feltöltési hiba (kód: ' . (int)$f['error'] . ').';
    else {
      $mime = mime_content_type($f['tmp_name']); // mime_content_type(): MIME becslés
      if (!isset($allowed[$mime])) $errors['file'] = 'Csak JPG/PNG/GIF tölthető fel.';
      elseif ($f['size'] > 2 * 1024 * 1024) $errors['file'] = 'Max 2MB.';
      else {
        $name = date('Ymd_His') . '_' . bin2hex(random_bytes(4)) . '.' . $allowed[$mime];
        $dest = $uploads . DIRECTORY_SEPARATOR . $name;
        // move_uploaded_file(): feltöltött fájl áthelyezése
        if (!move_uploaded_file($f['tmp_name'], $dest)) $errors['file'] = 'Mentés sikertelen.';
        else {
          header('Location: ' . $_SERVER['PHP_SELF']);
          exit;
        }
      }
    }
  }
}

if (isset($_GET['delete'])) {
  $fn = (string)$_GET['delete'];
  if (preg_match('/^[A-Za-z0-9_.-]+$/', $fn)) {
    $p = $uploads . DIRECTORY_SEPARATOR . $fn;
    if (is_file($p)) unlink($p);
  }
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$files = [];
foreach (scandir($uploads) as $fn) { // scandir(): könyvtár listázása
  if ($fn === '.' || $fn === '..') continue;
  if (is_file($uploads . DIRECTORY_SEPARATOR . $fn)) $files[] = $fn;
}
rsort($files);
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session04 / Task07 – Upload</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task07 – Képfeltöltés (uploads)</h1>
  </header>

  <div class="card notice">
    <p>Demó: fájlfeltöltés, mentés <code>uploads/</code> mappába, listázás és törlés.</p>
  </div>

  <div class="card">
    <form method="post" enctype="multipart/form-data" novalidate>
      <label for="file">Kép (JPG/PNG/GIF, max 2MB)</label>
      <input id="file" name="file" type="file" accept="image/*">
      <?php if (isset($errors['file'])): ?><div class="field-error"><?php echo h($errors['file']); ?></div><?php endif; ?>
      <div style="margin-top:12px"><button type="submit">Feltöltés</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Feltöltött fájlok</h2>
    <?php if (!$files): ?><p class="small">Nincs fájl.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Fájl</th>
            <th>Előnézet</th>
            <th>Művelet</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($files as $fn): ?>
            <tr>
              <td class="small"><code><?php echo h($fn); ?></code></td>
              <td><img src="<?php echo h('uploads/' . $fn); ?>" alt="" style="max-height:80px;max-width:160px"></td>
              <td><a href="?delete=<?php echo h(urlencode($fn)); ?>">Törlés</a></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>
  <footer class="small">Generated by PHP</footer>
</body>

</html>