<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$months = [
  'Január',
  'Február',
  'Március',
  'Április',
  'Május',
  'Június',
  'Július',
  'Augusztus',
  'Szeptember',
  'Október',
  'November',
  'December'
];

// count(): tömb elemszámának lekérdezése
$monthCount = count($months);
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>01 – Hónapok táblázatban</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Hónapok táblázatban</h1>
  </header>

  <div class="card notice">
    <p>Ez a feladat egy egyszerű, indexelt tömböt és a <code>foreach</code> bejárást gyakoroltatja.</p>
  </div>

  <div class="card">
    <p><strong>Összesen:</strong> <?php echo (int)$monthCount; ?> hónap</p>
    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>Hónap</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($months as $i => $m): ?>
          <tr>
            <td><?php echo (int)($i + 1); ?></td>
            <td><?php echo h($m); ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>