<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$scoreRaw = $_POST['score'] ?? '';
$score = null;
$error = '';
$label = '';
$missing = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $val = filter_var($scoreRaw, FILTER_VALIDATE_INT);
  if ($val === false) {
    $error = 'Kérem, egész pontszámot adjon meg.';
  } else {
    $score = (int)$val;
    if ($score < 0 || $score > 100) {
      $error = 'A pontszám csak 0 és 100 közötti lehet.';
    } else {
      if ($score <= 49) $label = 'elégtelen';
      elseif ($score <= 64) $label = 'elégséges';
      elseif ($score <= 79) $label = 'közepes';
      elseif ($score <= 89) $label = 'jó';
      else $label = 'jeles';

      // Missing to next category
      $thresholds = [50, 65, 80, 90, 101]; // 101 means no next
      foreach ($thresholds as $t) {
        if ($score < $t) {
          $missing = $t - $score;
          if ($t === 101) $missing = 0;
          break;
        }
      }
    }
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>05 – Pontszám → Jegy</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Pontszám → érdemjegy</h1>
  </header>

  <div class="card">
    <form method="post" action="">
      <label for="score">Pontszám (0–100)</label>
      <input id="score" name="score" type="number" min="0" max="100" value="<?php echo h((string)$scoreRaw); ?>">
      <div style="margin-top:12px">
        <button type="submit">Értékelés</button>
      </div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($error === '' && $score !== null): ?>
    <div class="card ok">
      <p><strong>Eredmény:</strong> <?php echo (int)$score; ?> pont → <?php echo h($label); ?></p>
      <?php if ($missing !== null && $missing > 0 && $score < 100): ?>
        <p class="small">A következő szinthez <?php echo (int)$missing; ?> pont hiányzik.</p>
      <?php elseif ($score === 100 || $label === 'jeles'): ?>
        <p class="small">Nincs következő szint.</p>
      <?php endif; ?>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>