<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/db.php';

$info = [];
$rows = [];
$error = null;

try {
  $mysqli = db();

  $info['server'] = $mysqli->server_info;
  $info['host'] = $mysqli->host_info;
  $info['charset'] = $mysqli->character_set_name();

  // Egyszerű SELECT (intro)
  $res = $mysqli->query('SELECT id, name, price_ft FROM products ORDER BY id');
  $rows = $res->fetch_all(MYSQLI_ASSOC);

  $mysqli->close();
} catch (Throwable $e) {
  $error = $e->getMessage();
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session09 / Task01 – Kapcsolódás + SELECT</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task01 – MySQLi kapcsolat + első SELECT</h1>
  </header>

  <div class="card notice">
    <p>Feladat: sikeres kapcsolódás, szerverinformációk kiírása és egy minta tábla lekérdezése (<code>products</code>).</p>
    <p class="small">Előkészítés: futtassa le a <code>schema.sql</code>-t, majd állítsa be a <code>config.php</code>-t.</p>
  </div>

  <?php if ($error): ?>
    <div class="card err"><strong>Kapcsolódási hiba:</strong> <?php echo h($error); ?></div>
  <?php else: ?>
    <div class="card ok">
      <h2>Kapcsolat OK</h2>
      <table>
        <tr>
          <th>Szerver</th>
          <td><?php echo h((string)$info['server']); ?></td>
        </tr>
        <tr>
          <th>Host</th>
          <td><?php echo h((string)$info['host']); ?></td>
        </tr>
        <tr>
          <th>Charset</th>
          <td><?php echo h((string)$info['charset']); ?></td>
        </tr>
      </table>
    </div>

    <div class="card">
      <h2>Termékek</h2>
      <?php if (!$rows): ?><p class="small">Nincs adat.</p>
      <?php else: ?>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Név</th>
              <th>Ár</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($rows as $r): ?>
              <tr>
                <td><?php echo (int)$r['id']; ?></td>
                <td><?php echo h((string)$r['name']); ?></td>
                <td><?php echo h(number_format((int)$r['price_ft'], 0, ',', ' ')); ?> Ft</td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      <?php endif; ?>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>