<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$raw = $_POST['text'] ?? '';
$freq = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $text = mb_strtolower((string)$raw, 'UTF-8');

  // preg_split(): szavakra bontás nem betű/szám karakterek mentén
  $words = preg_split('/[^\p{L}\p{N}]+/u', $text, -1, PREG_SPLIT_NO_EMPTY);

  // array_count_values(): előfordulások számolása (string/int tömbre)
  $counts = array_count_values($words);

  // arsort(): érték szerinti csökkenő rendezés
  arsort($counts);

  $freq = $counts;
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>08 – Szógyakoriság</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Szógyakoriság számítása</h1>
  </header>

  <div class="card">
    <form method="post">
      <label for="text">Szöveg</label>
      <textarea id="text" name="text" rows="5" style="width:100%"><?php echo h((string)$raw); ?></textarea>
      <div style="margin-top:12px"><button type="submit">Elemzés</button></div>
    </form>
  </div>

  <?php if ($freq !== null): ?>
    <div class="card ok">
      <table>
        <thead>
          <tr>
            <th>Szó</th>
            <th>Darab</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($freq as $word => $count): ?>
            <tr>
              <td><?php echo h((string)$word); ?></td>
              <td><?php echo (int)$count; ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>