<?php

declare(strict_types=1);
require_once __DIR__ . '/controller.php';

$title = 'Task06 – Kontroller + nézet (külön fájlok)';
$data = ['name' => '', 'email' => '', 'msg' => ''];
$errors = [];
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  [$data, $errors] = handle_contact_form($_POST);
  if (!$errors) $success = true;
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo h($title); ?></title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1><?php echo h($title); ?></h1>
  </header>

  <div class="card notice">
    <p>A feldolgozás (validáció) a <code>controller.php</code>-ban van, a form HTML a <code>view.php</code>-ban.</p>
  </div>

  <?php include __DIR__ . '/view.php'; ?>

  <?php if ($success): ?>
    <div class="card ok">
      <h2>Sikeres beküldés</h2>
      <table>
        <tr>
          <th>Név</th>
          <td><?php echo h($data['name']); ?></td>
        </tr>
        <tr>
          <th>E-mail</th>
          <td><?php echo h($data['email']); ?></td>
        </tr>
        <tr>
          <th>Üzenet</th>
          <td><?php echo h($data['msg']); ?></td>
        </tr>
      </table>
    </div>
  <?php elseif ($_SERVER['REQUEST_METHOD'] === 'POST' && $errors): ?>
    <div class="card err"><strong>Hiba:</strong> Kérem, javítsa a mezőket.</div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>