<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$raw = $_POST['numbers'] ?? '';
$error = '';
$nums = [];
$stats = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  // explode(): string feldarabolása elválasztó mentén tömbbé
  $parts = explode(',', (string)$raw);

  // array_map(): minden elemre lefuttat egy függvényt (itt trim + float validálás)
  $parts = array_map('trim', $parts);

  foreach ($parts as $p) {
    if ($p === '') continue;
    $v = filter_var($p, FILTER_VALIDATE_FLOAT);
    if ($v === false) {
      $error = 'A megadott lista tartalmaz érvénytelen számot: ' . $p;
      break;
    }
    $nums[] = (float)$v;
  }

  if ($error === '' && count($nums) === 0) {
    $error = 'Kérem, adjon meg legalább 1 számot.';
  }

  if ($error === '') {
    // array_sum(): elemek összege, min()/max(): minimum/maximum
    $sum = array_sum($nums);
    $count = count($nums);
    $avg = $sum / $count;

    $stats = [
      'count' => $count,
      'sum' => $sum,
      'avg' => $avg,
      'min' => min($nums),
      'max' => max($nums),
    ];
  }
}

function nf(float $v): string
{
  return rtrim(rtrim(number_format($v, 6, '.', ''), '0'), '.');
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>02 – Számok statisztikája</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Számok statisztikája (CSV → tömb)</h1>
  </header>

  <div class="card">
    <form method="post">
      <label for="numbers">Számok vesszővel elválasztva</label>
      <input id="numbers" name="numbers" type="text" value="<?php echo h((string)$raw); ?>" placeholder="pl. 1, 2.5, -3, 10">
      <div style="margin-top:12px"><button type="submit">Számítás</button></div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($stats !== null): ?>
    <div class="card ok">
      <p class="small"><strong>Beolvasott értékek:</strong> <?php echo h(implode(', ', array_map('nf', $nums))); ?></p>

      <table>
        <tr>
          <th>Elemszám</th>
          <td><?php echo (int)$stats['count']; ?></td>
        </tr>
        <tr>
          <th>Összeg</th>
          <td><?php echo h(nf((float)$stats['sum'])); ?></td>
        </tr>
        <tr>
          <th>Átlag</th>
          <td><?php echo h(nf((float)$stats['avg'])); ?></td>
        </tr>
        <tr>
          <th>Minimum</th>
          <td><?php echo h(nf((float)$stats['min'])); ?></td>
        </tr>
        <tr>
          <th>Maximum</th>
          <td><?php echo h(nf((float)$stats['max'])); ?></td>
        </tr>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>