<?php

declare(strict_types=1);
require_once __DIR__ . '/lib.php';

$page = (string)($_GET['page'] ?? 'home');
$allowed = ['home', 'about', 'contact'];
if (!in_array($page, $allowed, true)) $page = 'home';

$title = 'Task05 – Mini router több oldallal';
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo h($title); ?></title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1><?php echo h($title); ?></h1>
  </header>

  <nav class="small">
    <a href="?page=home">Kezdőlap</a>
    <a href="?page=about">Névjegy</a>
    <a href="?page=contact">Kapcsolat</a>
  </nav>

  <?php
  // include: a kiválasztott oldal beillesztése
  include __DIR__ . '/pages/' . $page . '.php';
  ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>