<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
// Asszociatív tömb: kulcs => érték
$products = [
  'Kenyér' => 899,
  'Tej' => 499,
  'Sajt' => 1299,
  'Alma' => 799,
];

$total = array_sum($products); // array_sum(): elemek összege (itt árak összege)

function money(int $v): string
{
  // number_format(): formázás ezreselválasztóval, tizedes nélkül
  return number_format($v, 0, ',', ' ') . ' Ft';
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>04 – Termékek és árak</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Termékek és árak (asszociatív tömb)</h1>
  </header>

  <div class="card">
    <table>
      <thead>
        <tr>
          <th>Termék</th>
          <th>Ár</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($products as $name => $price): ?>
          <tr>
            <td><?php echo h($name); ?></td>
            <td><?php echo h(money((int)$price)); ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <th>Összesen</th>
          <th><?php echo h(money((int)$total)); ?></th>
        </tr>
      </tfoot>
    </table>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>