<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
    $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
    if (!is_dir($dir)) {
        mkdir($dir, 0777, true);
    }
    return $dir;
}
?>
<?php
$data = ensure_dir('data');
$file = $data . DIRECTORY_SEPARATOR . 'access.log';

// ha nincs log, generálunk demót
if (!is_file($file)) {
    $demo = [];
    for ($i = 0; $i < 80; $i++) {
        $ts = time() - random_int(0, 6) * 86400 - random_int(0, 86399);
        $demo[] = date('Y-m-d H:i:s', $ts) . " | demo event" . PHP_EOL;
    }
    file_put_contents($file, implode('', $demo), LOCK_EX);
}

if (isset($_GET['add'])) {
    file_put_contents($file, date('Y-m-d H:i:s') . " | user action" . PHP_EOL, FILE_APPEND | LOCK_EX);
    header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
    exit;
}
if (isset($_GET['clear'])) {
    unlink($file);
    header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
    exit;
}

$lines = file($file, FILE_IGNORE_NEW_LINES);
$perDay = [];
foreach ($lines as $l) {
    $day = substr($l, 0, 10);
    if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $day)) continue;
    $perDay[$day] = ($perDay[$day] ?? 0) + 1;
}
ksort($perDay);
?>
<!doctype html>
<html lang="hu">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Session04 / Task06 – Log stat</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <header>
        <h1>Task06 – Logfájl elemzés (napi darabszám)</h1>
    </header>

    <div class="card notice">
        <p>Fájl: <code>data/access.log</code> · <a href="?add=1">Új sor</a> · <a href="?clear=1">Törlés (demo újragenerálódik)</a></p>
    </div>

    <div class="card">
        <table>
            <thead>
                <tr>
                    <th>Dátum</th>
                    <th>Események száma</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($perDay as $d => $c): ?><tr>
                        <td><?php echo h($d); ?></td>
                        <td><?php echo (int)$c; ?></td>
                    </tr><?php endforeach; ?>
            </tbody>
        </table>
        <p class="small">Összes sor: <?php echo (int)count($lines); ?></p>
    </div>
    <footer class="small">Generated by PHP</footer>
</body>

</html>