<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/db.php';

$name = (string)($_POST['name'] ?? '');
$neptun = (string)($_POST['neptun'] ?? '');
$errors = [];
$flash = null;
$error = null;
$rows = [];

try {
  $mysqli = db();

  if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $n = trim($name);
    $np = strtoupper(trim($neptun));

    if ($n === '') $errors['name'] = 'Kérem, adja meg a nevet.';
    if (!preg_match('/^[A-Z0-9]{6}$/', $np)) $errors['neptun'] = 'A Neptun 6 karakter (A-Z/0-9).';

    if (!$errors) {
      // Prepared statement (SQL injection ellen)
      $stmt = $mysqli->prepare('INSERT INTO students (name, neptun) VALUES (?, ?)');
      $stmt->bind_param('ss', $n, $np);
      $stmt->execute();
      $stmt->close();

      header('Location: ' . $_SERVER['PHP_SELF'] . '?ok=1'); // PRG
      exit;
    }
  }

  $flash = isset($_GET['ok']) ? 'Hallgató elmentve.' : null;

  $res = $mysqli->query('SELECT id, name, neptun, created_at FROM students ORDER BY created_at DESC');
  $rows = $res->fetch_all(MYSQLI_ASSOC);

  $mysqli->close();
} catch (Throwable $e) {
  $error = $e->getMessage();
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session09 / Task02 – INSERT + lista</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task02 – INSERT űrlap + lista (prepared statement)</h1>
  </header>

  <div class="card notice">
    <p>Feladat: új hallgató felvétele MySQL-be és listázás. Kötelező a prepared statement használata.</p>
  </div>

  <?php if ($error): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div><?php endif; ?>
  <?php if ($flash): ?><div class="card ok"><strong><?php echo h($flash); ?></strong></div><?php endif; ?>

  <div class="card">
    <h2>Új hallgató</h2>
    <form method="post" novalidate class="row" style="align-items:end">
      <div>
        <label for="name">Név</label>
        <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
        <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="neptun">Neptun</label>
        <input id="neptun" name="neptun" type="text" value="<?php echo h($neptun); ?>">
        <?php if (isset($errors['neptun'])): ?><div class="field-error"><?php echo h($errors['neptun']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Mentés</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Hallgatók (<?php echo (int)count($rows); ?>)</h2>
    <?php if (!$rows): ?><p class="small">Nincs adat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Név</th>
            <th>Neptun</th>
            <th>Létrehozva</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($rows as $r): ?>
            <tr>
              <td><?php echo (int)$r['id']; ?></td>
              <td><?php echo h((string)$r['name']); ?></td>
              <td><code><?php echo h((string)$r['neptun']); ?></code></td>
              <td class="small"><?php echo h((string)$r['created_at']); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>