<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
  $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
  if (!is_dir($dir)) {
    mkdir($dir, 0777, true);
  }
  return $dir;
}
?>
<?php
$data = ensure_dir('data');
$file = $data . DIRECTORY_SEPARATOR . 'config.json';

$defaults = ['site_title' => 'Demo alkalmazás', 'items_per_page' => 10, 'maintenance' => false];

if (!is_file($file)) {
  file_put_contents($file, json_encode($defaults, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), LOCK_EX);
}

$config = $defaults;
$parsed = json_decode((string)file_get_contents($file), true);
if (is_array($parsed)) $config = array_merge($config, $parsed); // array_merge(): defaults felülírása

$errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $title = trim((string)($_POST['site_title'] ?? ''));
  $ippRaw = (string)($_POST['items_per_page'] ?? '10');
  $maint = isset($_POST['maintenance']);
  $ipp = filter_var($ippRaw, FILTER_VALIDATE_INT);

  if ($title === '') $errors['site_title'] = 'Kérem, adja meg a címet.';
  if ($ipp === false || $ipp < 1 || $ipp > 100) $errors['items_per_page'] = '1–100 közötti egész szám.';

  if (!$errors) {
    $config = ['site_title' => $title, 'items_per_page' => (int)$ipp, 'maintenance' => (bool)$maint];
    file_put_contents($file, json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), LOCK_EX);
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session04 / Task08 – Config</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task08 – Konfiguráció JSON fájlban</h1>
  </header>

  <div class="card notice">
    <p>Beállítások fájlban: <code>data/config.json</code></p>
  </div>

  <div class="card">
    <form method="post" novalidate>
      <label for="site_title">Oldalcím</label>
      <input id="site_title" name="site_title" type="text" value="<?php echo h((string)$config['site_title']); ?>">
      <?php if (isset($errors['site_title'])): ?><div class="field-error"><?php echo h($errors['site_title']); ?></div><?php endif; ?>

      <label for="items_per_page">Elemek oldalanként (1–100)</label>
      <input id="items_per_page" name="items_per_page" type="number" min="1" max="100" value="<?php echo (int)$config['items_per_page']; ?>">
      <?php if (isset($errors['items_per_page'])): ?><div class="field-error"><?php echo h($errors['items_per_page']); ?></div><?php endif; ?>

      <label style="display:inline-flex;align-items:center;gap:8px;margin-top:10px">
        <input type="checkbox" name="maintenance" <?php echo ((bool)$config['maintenance']) ? 'checked' : ''; ?>>
        Karbantartási mód
      </label>

      <div style="margin-top:12px"><button type="submit">Mentés</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Aktuális értékek</h2>
    <table>
      <tr>
        <th>site_title</th>
        <td><?php echo h((string)$config['site_title']); ?></td>
      </tr>
      <tr>
        <th>items_per_page</th>
        <td><?php echo (int)$config['items_per_page']; ?></td>
      </tr>
      <tr>
        <th>maintenance</th>
        <td><?php echo ((bool)$config['maintenance']) ? 'true' : 'false'; ?></td>
      </tr>
    </table>
  </div>
  <footer class="small">Generated by PHP</footer>
</body>

</html>