<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Value\Email;
use App\Value\Money;
use App\Domain\Invoice;
use App\Domain\InvoiceItem;

Autoloader::register('App', __DIR__ . '/src');

$emailRaw = (string)($_POST['email'] ?? '');
$nameRaw  = (string)($_POST['name'] ?? '');
$priceRaw = (string)($_POST['price'] ?? '');
$qtyRaw   = (string)($_POST['qty'] ?? '1');

$errors = [];
$invoice = null;
$result = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  try {
    $email = new Email($emailRaw);
    $invoice = new Invoice($email);

    $name = trim($nameRaw);
    $price = filter_var($priceRaw, FILTER_VALIDATE_INT);
    $qty = filter_var($qtyRaw, FILTER_VALIDATE_INT);

    if ($name === '') $errors['name'] = 'Kérem, adja meg a tétel nevét.';
    if ($priceRaw === '' || $price === false || $price < 0) $errors['price'] = 'Az ár legyen 0 vagy pozitív egész.';
    if ($qtyRaw === '' || $qty === false || $qty <= 0) $errors['qty'] = 'A mennyiség legyen pozitív egész.';

    if (!$errors) {
      $invoice->addItem(new InvoiceItem($name, new Money((int)$price), (int)$qty));
      $result = ['net' => $invoice->totalNet(), 'gross' => $invoice->totalGross(0.27)];
    }
  } catch (Throwable $e) {
    $errors['email'] = $e->getMessage();
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session07 / Task02 – Value Objects</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task02 – Value object-ek (Email, Money) + Invoice</h1>
  </header>

  <div class="card notice">
    <p>Validált, immutábilis értékobjektumok + összetett domain objektum.</p>
  </div>

  <div class="card">
    <form method="post" novalidate>
      <label for="email">Vevő e-mail</label>
      <input id="email" name="email" type="text" value="<?php echo h($emailRaw); ?>">
      <?php if (isset($errors['email'])): ?><div class="field-error"><?php echo h($errors['email']); ?></div><?php endif; ?>

      <div class="row">
        <div>
          <label for="name">Tétel neve</label>
          <input id="name" name="name" type="text" value="<?php echo h($nameRaw); ?>">
          <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
        </div>
        <div>
          <label for="price">Egységár (Ft)</label>
          <input id="price" name="price" type="number" min="0" value="<?php echo h($priceRaw); ?>">
          <?php if (isset($errors['price'])): ?><div class="field-error"><?php echo h($errors['price']); ?></div><?php endif; ?>
        </div>
      </div>

      <label for="qty">Mennyiség</label>
      <input id="qty" name="qty" type="number" min="1" value="<?php echo h($qtyRaw); ?>">
      <?php if (isset($errors['qty'])): ?><div class="field-error"><?php echo h($errors['qty']); ?></div><?php endif; ?>

      <div style="margin-top:12px"><button type="submit">Számítás</button></div>
    </form>
  </div>

  <?php if ($result && $invoice): ?>
    <div class="card ok">
      <h2>Összegzés</h2>
      <p><strong>Vevő:</strong> <?php echo h((string)$invoice->customerEmail()); ?></p>
      <table>
        <thead>
          <tr>
            <th>Tétel</th>
            <th>Egységár</th>
            <th>Mennyiség</th>
            <th>Nettó</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($invoice->items() as $it): ?>
            <tr>
              <td><?php echo h($it->name()); ?></td>
              <td><?php echo h($it->unitPrice()->format()); ?></td>
              <td><?php echo (int)$it->qty(); ?></td>
              <td><?php echo h($it->subtotal()->format()); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
        <tfoot>
          <tr>
            <th colspan="3">Összesen nettó</th>
            <th><?php echo h($result['net']->format()); ?></th>
          </tr>
          <tr>
            <th colspan="3">Összesen bruttó (27% ÁFA)</th>
            <th><?php echo h($result['gross']->format()); ?></th>
          </tr>
        </tfoot>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>