<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$aRaw = $_POST['a'] ?? '';
$bRaw = $_POST['b'] ?? '';
$op = (string)($_POST['op'] ?? '+');

$resultText = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $a = filter_var($aRaw, FILTER_VALIDATE_FLOAT); // A filter_var() ellenőrzi, hogy az adott változó érvényes lebegőpontos szám-e; ha nem, akkor false értéket ad vissza.
  $b = filter_var($bRaw, FILTER_VALIDATE_FLOAT);

  if ($a === false || $b === false) {
    $error = 'Kérem, két érvényes számot adjon meg.';
  } else {
    switch ($op) {
      case '+':
        $res = $a + $b;
        break;
      case '-':
        $res = $a - $b;
        break;
      case '*':
        $res = $a * $b;
        break;
      case '/':
        if ((float)$b === 0.0) {
          $error = '0-val nem lehet osztani.';
          $res = null;
        } else {
          $res = $a / $b;
        }
        break;
      default:
        $error = 'Ismeretlen művelet.';
        $res = null;
    }

    if ($error === '' && $res !== null) {
      $resultText = sprintf('Eredmény: %s %s %s = %s', $a, $op, $b, $res); // A sprintf() formázott sztringet készít, ahol a %s helyére sorrendben a megadott változók értékei kerülnek.
    }
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>04 – POST számológép</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Egyszerű számológép (POST)</h1>
  </header>

  <div class="card">
    <form method="post" action="">
      <label for="a">a</label>
      <input id="a" name="a" type="text" inputmode="decimal" value="<?php echo h((string)$aRaw); ?>">

      <label for="op">Művelet</label>
      <select id="op" name="op">
        <?php
        $ops = ['+', '-', '*', '/'];
        foreach ($ops as $o) {
          $sel = ($op === $o) ? 'selected' : '';
          echo "<option value=\"" . h($o) . "\" $sel>" . h($o) . "</option>";
        }
        ?>
      </select>

      <label for="b">b</label>
      <input id="b" name="b" type="text" inputmode="decimal" value="<?php echo h((string)$bRaw); ?>">

      <div style="margin-top:12px">
        <button type="submit">Számítás</button>
      </div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($resultText !== ''): ?>
    <div class="card ok"><?php echo h($resultText); ?></div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>