<?php

declare(strict_types=1); // A strict_types=1 bekapcsolja a szigorú típusellenőrzést, így a PHP nem végez automatikus típuskonverziót a függvényparamétereknél és visszatérési értékeknél.
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>01 – Hello, PHP</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Welcome to PHP lab!</h1>
  </header>

  <div class="card notice">
    <p><strong>Aktuális dátum és idő:</strong>
      <?php echo date('Y-m-d H:i:s'); ?>
    </p>
    <p><strong>PHP verzió:</strong>
      <?php echo PHP_VERSION; ?>
    </p>
  </div>

  <footer class="small">
    Generated by PHP
  </footer>
</body>

</html>