<?php

declare(strict_types=1);

session_start();

require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Domain\Student;

Autoloader::register('App', __DIR__ . '/src');

$name = (string)($_POST['name'] ?? '');
$neptun = (string)($_POST['neptun'] ?? '');
$pointsRaw = (string)($_POST['points'] ?? '0');

$errors = [];
$error = null;

try {
  $db = Db::conn();

  if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'create') {
    $p = filter_var($pointsRaw, FILTER_VALIDATE_INT);
    if ($pointsRaw === '' || $p === false) $errors['points'] = 'A pont legyen egész.';
    if (!$errors) {
      $s = Student::create($name, $neptun, (int)$p);
      $s->insert($db);
      flash_set('Hallgató elmentve (ID: ' . $s->id . ').');
      header('Location: ' . $_SERVER['PHP_SELF']);
      exit;
    }
  }

  if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'delete') {
    $id = (int)($_POST['id'] ?? 0);
    Student::deleteById($db, $id);
    flash_set('Hallgató törölve.');
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  }

  $students = Student::all($db);
} catch (Throwable $e) {
  $error = $e->getMessage();
  $students = [];
}

$flash = flash_get();
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session10 / Task03 – Active Record</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task03 – MySQLi + OOP: Active Record stílus (összehasonlításhoz)</h1>
  </header>

  <div class="card notice">
    <p>Ebben a feladatban az entitás (<code>Student</code>) tartalmaz statikus DB metódusokat (Active Record jelleg). Tanítási cél: előny/hátrány megbeszélése a Repository-hoz képest.</p>
  </div>

  <?php if ($error): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div><?php endif; ?>
  <?php if ($flash): ?><div class="card ok"><strong><?php echo h($flash); ?></strong></div><?php endif; ?>

  <div class="card">
    <h2>Új hallgató</h2>
    <form method="post" novalidate class="row" style="align-items:end">
      <input type="hidden" name="action" value="create">
      <div>
        <label for="name">Név</label>
        <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
        <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="neptun">Neptun</label>
        <input id="neptun" name="neptun" type="text" value="<?php echo h($neptun); ?>">
        <?php if (isset($errors['neptun'])): ?><div class="field-error"><?php echo h($errors['neptun']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="points">Pont (0–100)</label>
        <input id="points" name="points" type="number" min="0" max="100" value="<?php echo h($pointsRaw); ?>">
        <?php if (isset($errors['points'])): ?><div class="field-error"><?php echo h($errors['points']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Mentés</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Hallgatók (<?php echo (int)count($students); ?>)</h2>
    <?php if (!$students): ?><p class="small">Nincs adat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Név</th>
            <th>Neptun</th>
            <th>Pont</th>
            <th>Idő</th>
            <th>Művelet</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($students as $s): ?>
            <tr>
              <td><?php echo (int)$s->id; ?></td>
              <td><?php echo h($s->name); ?></td>
              <td><code><?php echo h($s->neptun); ?></code></td>
              <td><?php echo (int)$s->points; ?></td>
              <td class="small"><?php echo h((string)$s->createdAt); ?></td>
              <td>
                <form method="post" style="margin:0" onsubmit="return confirm('Törli?')">
                  <input type="hidden" name="action" value="delete">
                  <input type="hidden" name="id" value="<?php echo (int)$s->id; ?>">
                  <button type="submit">Törlés</button>
                </form>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>