<?php

declare(strict_types=1);

session_start();

require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Repo\MysqliProductRepository;
use App\Service\ProductService;

Autoloader::register('App', __DIR__ . '/src');

$name = (string)($_POST['name'] ?? '');
$priceRaw = (string)($_POST['price'] ?? '');
$errors = [];
$error = null;

try {
  $db = Db::conn();
  $service = new ProductService(new MysqliProductRepository($db));

  if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $p = filter_var($priceRaw, FILTER_VALIDATE_INT);
    if (trim($name) === '') $errors['name'] = 'A név kötelező.';
    if ($priceRaw === '' || $p === false || $p < 0) $errors['price'] = 'Az ár legyen 0 vagy pozitív egész.';

    if (!$errors) {
      $service->create($name, (int)$p);
      flash_set('Termék elmentve.');
      header('Location: ' . $_SERVER['PHP_SELF']);
      exit; // PRG
    }
  }

  $items = $service->list();
} catch (Throwable $e) {
  $error = $e->getMessage();
  $items = [];
}

$flash = flash_get();
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session10 / Task01 – Repo + Service</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task01 – MySQLi + OOP: Repository + Service (Products)</h1>
  </header>

  <div class="card notice">
    <p>Struktúra: <code>Domain</code> (Product) + <code>Repo</code> (MysqliProductRepository) + <code>Service</code> (ProductService).</p>
  </div>

  <?php if ($error): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div><?php endif; ?>
  <?php if ($flash): ?><div class="card ok"><strong><?php echo h($flash); ?></strong></div><?php endif; ?>

  <div class="card">
    <h2>Új termék</h2>
    <form method="post" novalidate class="row" style="align-items:end">
      <div>
        <label for="name">Név</label>
        <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
        <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="price">Ár (Ft)</label>
        <input id="price" name="price" type="number" min="0" value="<?php echo h($priceRaw); ?>">
        <?php if (isset($errors['price'])): ?><div class="field-error"><?php echo h($errors['price']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Mentés</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Termékek (<?php echo (int)count($items); ?>)</h2>
    <?php if (!$items): ?><p class="small">Nincs adat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Név</th>
            <th>Ár</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($items as $p): ?>
            <tr>
              <td><?php echo (int)$p->id(); ?></td>
              <td><?php echo h($p->name()); ?></td>
              <td><?php echo h(number_format($p->priceFt(), 0, ',', ' ')); ?> Ft</td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>