<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
  $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
  if (!is_dir($dir)) {
    mkdir($dir, 0777, true);
  }
  return $dir;
}
?>
<?php
$data = ensure_dir('data');
$file = $data . DIRECTORY_SEPARATOR . 'users.json';

function load_users(string $file): array
{
  if (!is_file($file)) return [];
  $raw = file_get_contents($file); // file_get_contents(): teljes fájl beolvasása
  $arr = json_decode((string)$raw, true); // json_decode(..., true): asszociatív tömb
  return is_array($arr) ? $arr : [];
}
function save_users(string $file, array $users): void
{
  $json = json_encode($users, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE); // json_encode(): tömb -> JSON
  file_put_contents($file, (string)$json, LOCK_EX);
}

$users = load_users($file);

$username = (string)($_POST['username'] ?? '');
$email = (string)($_POST['email'] ?? '');
$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $username = trim($username);
  $email = trim($email);

  if ($username === '') $errors['username'] = 'Kérem, adjon meg felhasználónevet.';
  elseif (mb_strlen($username, 'UTF-8') < 3) $errors['username'] = 'Minimum 3 karakter.';

  if ($email === '') $errors['email'] = 'Kérem, adjon meg e-mail címet.';
  elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) $errors['email'] = 'Hibás e-mail formátum.';

  foreach ($users as $u) {
    if (mb_strtolower((string)($u['email'] ?? ''), 'UTF-8') === mb_strtolower($email, 'UTF-8')) {
      $errors['email'] = 'Ez az e-mail már létezik.';
      break;
    }
  }

  if (!$errors) {
    $users[] = [
      'id' => bin2hex(random_bytes(4)), // random_bytes(): biztonságos random ID
      'username' => $username,
      'email' => $email,
      'created_at' => date('Y-m-d H:i:s'),
    ];
    save_users($file, $users);
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  }
}

if (isset($_GET['clear'])) {
  if (is_file($file)) unlink($file);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session04 / Task03 – JSON users</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task03 – Felhasználók mentése JSON-be</h1>
  </header>

  <div class="card">
    <form method="post" novalidate>
      <div class="row">
        <div>
          <label for="username">Felhasználónév</label>
          <input id="username" name="username" type="text" value="<?php echo h($username); ?>">
          <?php if (isset($errors['username'])): ?><div class="field-error"><?php echo h($errors['username']); ?></div><?php endif; ?>
        </div>
        <div>
          <label for="email">E-mail</label>
          <input id="email" name="email" type="text" value="<?php echo h($email); ?>">
          <?php if (isset($errors['email'])): ?><div class="field-error"><?php echo h($errors['email']); ?></div><?php endif; ?>
        </div>
      </div>
      <div style="margin-top:12px"><button type="submit">Mentés</button></div>
    </form>
    <p class="small">Fájl: <code>data/users.json</code> · <a href="?clear=1">Törlés</a></p>
  </div>

  <div class="card">
    <h2>Lista (<?php echo (int)count($users); ?> db)</h2>
    <?php if (!$users): ?><p class="small">Nincs adat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Felhasználónév</th>
            <th>E-mail</th>
            <th>Létrehozva</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach (array_reverse($users) as $u): ?>
            <tr>
              <td class="small"><code><?php echo h((string)$u['id']); ?></code></td>
              <td><?php echo h((string)$u['username']); ?></td>
              <td><?php echo h((string)$u['email']); ?></td>
              <td class="small"><?php echo h((string)$u['created_at']); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>
  <footer class="small">Generated by PHP</footer>
</body>

</html>