<?php

declare(strict_types=1);

require_once __DIR__ . '/helpers.php';
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Domain\ProductQuery;
use App\Repo\ProductSearchRepository;
use App\Service\ProductSearchService;

Autoloader::register('App', __DIR__ . '/src');

$q = trim((string)($_GET['q'] ?? ''));
$page = (int)(filter_var((string)($_GET['page'] ?? '1'), FILTER_VALIDATE_INT) ?: 1);
$perPage = 5;

$error = null;

try {
  $db = Db::conn();
  $service = new ProductSearchService(new ProductSearchRepository($db));

  $query = new ProductQuery($q, $page, $perPage);
  $data = $service->search($query);
} catch (Throwable $e) {
  $error = $e->getMessage();
  $data = ['total' => 0, 'pages' => 1, 'rows' => []];
  $query = new ProductQuery($q, $page, $perPage);
}

function pageLink(int $p, string $q): string
{
  return '?q=' . urlencode($q) . '&page=' . $p;
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session10 / Task05 – Query object + pagination</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task05 – MySQLi + OOP: Query object + lapozás service-ben</h1>
  </header>

  <div class="card notice">
    <p>A keresés paramétereit egy <code>ProductQuery</code> objektum fogja össze, a Service pedig kezeli a lapozási logikát.</p>
  </div>

  <?php if ($error): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div><?php endif; ?>

  <div class="card">
    <form method="get" class="row" style="align-items:end">
      <div>
        <label for="q">Keresés</label>
        <input id="q" name="q" type="text" value="<?php echo h($query->q); ?>">
      </div>
      <div><button type="submit">Keresés</button></div>
    </form>
    <p class="small">Találatok: <strong><?php echo (int)$data['total']; ?></strong></p>
  </div>

  <div class="card">
    <h2>Lista</h2>
    <?php if (!$data['rows']): ?><p class="small">Nincs találat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Név</th>
            <th>Ár</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($data['rows'] as $r): ?>
            <tr>
              <td><?php echo (int)$r['id']; ?></td>
              <td><?php echo h((string)$r['name']); ?></td>
              <td><?php echo h(number_format((int)$r['price_ft'], 0, ',', ' ')); ?> Ft</td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>

    <div class="small">
      Oldal:
      <?php for ($p = 1; $p <= (int)$data['pages']; $p++): ?>
        <?php if ($p === $query->page): ?>
          <strong><?php echo $p; ?></strong>
        <?php else: ?>
          <a href="<?php echo h(pageLink($p, $query->q)); ?>"><?php echo $p; ?></a>
        <?php endif; ?>
        <?php if ($p < (int)$data['pages']) echo ' · '; ?>
      <?php endfor; ?>
    </div>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>