<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
    $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
    if (!is_dir($dir)) {
        mkdir($dir, 0777, true);
    }
    return $dir;
}
?>
<?php
$data = ensure_dir('data');
$cache = $data . DIRECTORY_SEPARATOR . 'primes_cache.json';

$nRaw = (string)($_GET['n'] ?? '5000');
$n = filter_var($nRaw, FILTER_VALIDATE_INT);
if ($n === false || $n < 100 || $n > 50000) $n = 5000;

$ttl = 30;
$now = time();

function is_prime(int $x): bool
{
    if ($x < 2) return false;
    if ($x === 2) return true;
    if ($x % 2 === 0) return false;
    $r = (int)floor(sqrt($x));
    for ($i = 3; $i <= $r; $i += 2) if ($x % $i === 0) return false;
    return true;
}

$fromCache = false;
$res = null;

if (is_file($cache)) {
    $d = json_decode((string)file_get_contents($cache), true);
    if (is_array($d) && isset($d['n'], $d['created_at'], $d['count'])) {
        if ((int)$d['n'] === $n && ($now - (int)$d['created_at']) <= $ttl) {
            $res = $d;
            $fromCache = true;
        }
    }
}

if ($res === null) {
    $t0 = microtime(true); // microtime(true): időmérés
    $count = 0;
    for ($i = 2; $i <= $n; $i++) if (is_prime($i)) $count++;
    $ms = (microtime(true) - $t0) * 1000.0;

    $res = ['n' => $n, 'created_at' => $now, 'count' => $count, 'elapsed_ms' => $ms];
    file_put_contents($cache, json_encode($res, JSON_PRETTY_PRINT), LOCK_EX);
}

if (isset($_GET['clear'])) {
    if (is_file($cache)) unlink($cache);
    header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
    exit;
}
?>
<!doctype html>
<html lang="hu">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Session04 / Task09 – Cache</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <header>
        <h1>Task09 – Egyszerű cache fájlban (prímek darabszáma)</h1>
    </header>

    <div class="card notice">
        <p>Cache fájl: <code>data/primes_cache.json</code> (TTL: <?php echo (int)$ttl; ?>s)</p>
    </div>

    <div class="card">
        <form method="get">
            <label for="n">N (100–50000)</label>
            <input id="n" name="n" type="number" min="100" max="50000" value="<?php echo (int)$n; ?>">
            <div style="margin-top:12px"><button type="submit">Számítás</button></div>
        </form>
        <p><a href="?clear=1">Cache törlése</a></p>
    </div>

    <div class="card">
        <p><strong>Forrás:</strong> <?php echo $fromCache ? '<span class="badge ok">cache</span>' : '<span class="badge notice">újraszámolás</span>'; ?></p>
        <p><strong>Prímek száma 2..<?php echo (int)$res['n']; ?>:</strong> <?php echo (int)$res['count']; ?></p>
        <?php if (!$fromCache): ?><p class="small">Számítási idő: <?php echo h(number_format((float)$res['elapsed_ms'], 2, ',', ' ')); ?> ms</p><?php endif; ?>
    </div>
    <footer class="small">Generated by PHP</footer>
</body>

</html>