<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$products = [
  'Kenyér',
  'Teljes kiőrlésű kenyér',
  'Tej 1.5%',
  'Tej 2.8%',
  'Sajt trappista',
  'Sajt füstölt',
  'Alma',
  'Körte',
];

$qRaw = $_GET['q'] ?? '';
$q = trim((string)$qRaw);

$matches = [];
if ($q !== '') {
  foreach ($products as $p) {
    // stripos(): részsztring keresése kis/nagybetűtől függetlenül
    if (stripos($p, $q) !== false) {
      $matches[] = $p;
    }
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>07 – Keresés tömbben</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Keresés tömbben (részsztring)</h1>
  </header>

  <div class="card">
    <form method="get">
      <label for="q">Keresett szöveg</label>
      <input id="q" name="q" type="text" value="<?php echo h($q); ?>" placeholder="pl. tej vagy sajt">
      <div style="margin-top:12px"><button type="submit">Keresés</button></div>
    </form>
  </div>

  <div class="card">
    <p><strong>Találatok:</strong> <?php echo (int)count($matches); ?></p>
    <?php if ($q === ''): ?>
      <p class="small">Kérem, adjon meg keresőkifejezést.</p>
    <?php elseif (count($matches) === 0): ?>
      <p class="small">Nincs találat.</p>
    <?php else: ?>
      <ul>
        <?php foreach ($matches as $m): ?>
          <li><?php echo h($m); ?></li>
        <?php endforeach; ?>
      </ul>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>