<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$raw = $_POST['words'] ?? '';
$minLenRaw = $_POST['minlen'] ?? '4';
$error = '';
$result = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $minLen = filter_var($minLenRaw, FILTER_VALIDATE_INT);
  if ($minLen === false || $minLen < 1) {
    $error = 'A minimális hossz csak pozitív egész lehet.';
  } else {
    // preg_split(): szöveg darabolása reguláris kifejezéssel (szóközök, vessző, pontosvessző)
    $parts = preg_split('/[\s,;]+/u', trim((string)$raw), -1, PREG_SPLIT_NO_EMPTY);

    // array_filter(): szűrés feltétel alapján
    $filtered = array_filter($parts, function (string $w) use ($minLen): bool {
      // mb_strlen(): UTF-8 kompatibilis karakterszám
      return mb_strlen($w, 'UTF-8') >= $minLen;
    });

    // array_values(): újraindexelés 0..n-1 (szebb megjelenítéshez)
    $result = [
      'all' => $parts,
      'filtered' => array_values($filtered),
      'minLen' => (int)$minLen,
    ];
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>03 – Szavak szűrése</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Szavak szűrése hossz alapján</h1>
  </header>

  <div class="card">
    <form method="post">
      <label for="words">Szavak (szóköz, vessző vagy pontosvessző elválasztással)</label>
      <textarea id="words" name="words" rows="4" style="width:100%"><?php echo h((string)$raw); ?></textarea>

      <label for="minlen">Minimális hossz</label>
      <input id="minlen" name="minlen" type="number" min="1" value="<?php echo h((string)$minLenRaw); ?>">

      <div style="margin-top:12px"><button type="submit">Szűrés</button></div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($result !== null): ?>
    <div class="card ok">
      <p><strong>Összes szó:</strong> <?php echo (int)count($result['all']); ?></p>
      <p><strong>Megfelelő szavak (≥ <?php echo (int)$result['minLen']; ?>):</strong> <?php echo (int)count($result['filtered']); ?></p>
      <p class="small"><strong>Eredmény:</strong> <?php echo h(implode(', ', $result['filtered'])); ?></p>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>