<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/db.php';

$title = (string)($_POST['title'] ?? '');
$body  = (string)($_POST['body'] ?? '');
$errors = [];
$flash = null;
$error = null;
$rows = [];

try {
  $mysqli = db();

  // DELETE (POST)
  if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'delete') {
    $id = (int)($_POST['id'] ?? 0);
    $stmt = $mysqli->prepare('DELETE FROM notes WHERE id = ?');
    $stmt->bind_param('i', $id);
    $stmt->execute();
    $stmt->close();
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  }

  // CREATE (POST)
  if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'create') {
    $t = trim($title);
    $b = trim($body);

    if ($t === '') $errors['title'] = 'A cím kötelező.';
    if ($b === '') $errors['body'] = 'A tartalom kötelező.';
    if (mb_strlen($t, 'UTF-8') > 120) $errors['title'] = 'A cím max 120 karakter.';

    if (!$errors) {
      $stmt = $mysqli->prepare('INSERT INTO notes (title, body) VALUES (?, ?)');
      $stmt->bind_param('ss', $t, $b);
      $stmt->execute();
      $stmt->close();
      header('Location: ' . $_SERVER['PHP_SELF'] . '?ok=1'); // PRG
      exit;
    }
  }

  $flash = isset($_GET['ok']) ? 'Jegyzet elmentve.' : null;

  $res = $mysqli->query('SELECT id, title, body, created_at FROM notes ORDER BY created_at DESC');
  $rows = $res->fetch_all(MYSQLI_ASSOC);

  $mysqli->close();
} catch (Throwable $e) {
  $error = $e->getMessage();
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session09 / Task03 – CRUD (C+R+D)</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task03 – CRUD alapok (Create + Read + Delete)</h1>
  </header>

  <div class="card notice">
    <p>Feladat: jegyzetek mentése adatbázisba, listázás, törlés (mind prepared statement-tel).</p>
    <p class="small">Szerkesztés külön feladatként jön a következő feladatban / következő héten, itt C/R/D a fókusz.</p>
  </div>

  <?php if ($error): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div><?php endif; ?>
  <?php if ($flash): ?><div class="card ok"><strong><?php echo h($flash); ?></strong></div><?php endif; ?>

  <div class="card">
    <h2>Új jegyzet</h2>
    <form method="post" novalidate>
      <input type="hidden" name="action" value="create">
      <label for="title">Cím</label>
      <input id="title" name="title" type="text" value="<?php echo h($title); ?>">
      <?php if (isset($errors['title'])): ?><div class="field-error"><?php echo h($errors['title']); ?></div><?php endif; ?>
      <label for="body">Tartalom</label>
      <textarea id="body" name="body" rows="5"><?php echo h($body); ?></textarea>
      <?php if (isset($errors['body'])): ?><div class="field-error"><?php echo h($errors['body']); ?></div><?php endif; ?>
      <div style="margin-top:12px"><button type="submit">Mentés</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Jegyzetek (<?php echo (int)count($rows); ?>)</h2>
    <?php if (!$rows): ?><p class="small">Nincs jegyzet.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Idő</th>
            <th>Cím</th>
            <th>Tartalom</th>
            <th>Művelet</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($rows as $r): ?>
            <tr>
              <td class="small"><?php echo h((string)$r['created_at']); ?></td>
              <td><?php echo h((string)$r['title']); ?></td>
              <td><?php echo h((string)$r['body']); ?></td>
              <td>
                <form method="post" style="margin:0" onsubmit="return confirm('Törli a jegyzetet?')">
                  <input type="hidden" name="action" value="delete">
                  <input type="hidden" name="id" value="<?php echo (int)$r['id']; ?>">
                  <button type="submit">Törlés</button>
                </form>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>