<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/TextStats.php';

$text = (string)($_POST['text'] ?? '');
$stats = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $stats = TextStats::fromPost($_POST); // static factory
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session06 / Task03 – Static vs instance</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task03 – Static metódusok és példány metódusok</h1>
  </header>

  <div class="card notice">
    <p>OOP: <code>TextStats</code> osztály. Példánymetódusok (charCount/wordCount) és statikus metódus (wordCountOf).</p>
  </div>

  <div class="card">
    <form method="post">
      <label for="text">Szöveg</label>
      <textarea id="text" name="text" rows="6" style="width:100%"><?php echo h($text); ?></textarea>
      <div style="margin-top:12px"><button type="submit">Elemzés</button></div>
    </form>
  </div>

  <?php if ($stats): ?>
    <div class="card ok">
      <h2>Eredmények</h2>
      <table>
        <tr>
          <th>Karakterek</th>
          <td><?php echo (int)$stats->charCount(); ?></td>
        </tr>
        <tr>
          <th>Szavak</th>
          <td><?php echo (int)$stats->wordCount(); ?></td>
        </tr>
        <tr>
          <th>Szavak (static)</th>
          <td><?php echo (int)TextStats::wordCountOf($stats->text()); ?></td>
        </tr>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>