<?php

declare(strict_types=1);

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php
$products = [
  'Kenyér' => 899,
  'Tej' => 499,
  'Sajt' => 1299,
  'Alma' => 799,
  'Csokoládé' => 649,
];

$mode = (string)($_GET['mode'] ?? 'as_is');
$sorted = $products;

switch ($mode) {
  case 'price_asc':
    // asort(): érték szerint rendezés, a kulcsok megtartásával
    asort($sorted);
    break;
  case 'price_desc':
    // arsort(): érték szerint csökkenő rendezés, a kulcsok megtartásával
    arsort($sorted);
    break;
  case 'name_asc':
    // ksort(): kulcs szerint rendezés
    ksort($sorted);
    break;
  case 'name_desc':
    // krsort(): kulcs szerint csökkenő rendezés
    krsort($sorted);
    break;
  default:
    // nincs rendezés
}

function money(int $v): string
{
  return number_format($v, 0, ',', ' ') . ' Ft';
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>05 – Rendezés</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Termékek rendezése</h1>
  </header>

  <div class="card">
    <p>Rendezés módja:</p>
    <ul>
      <li><a href="?mode=as_is">Eredeti</a></li>
      <li><a href="?mode=price_asc">Ár szerint növekvő</a></li>
      <li><a href="?mode=price_desc">Ár szerint csökkenő</a></li>
      <li><a href="?mode=name_asc">Név szerint A→Z</a></li>
      <li><a href="?mode=name_desc">Név szerint Z→A</a></li>
    </ul>
  </div>

  <div class="card">
    <table>
      <thead>
        <tr>
          <th>Termék</th>
          <th>Ár</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($sorted as $name => $price): ?>
          <tr>
            <td><?php echo h($name); ?></td>
            <td><?php echo h(money((int)$price)); ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>