<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$nRaw = $_POST['n'] ?? '';
$n = null;
$error = '';
$props = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $val = filter_var($nRaw, FILTER_VALIDATE_INT);
  if ($val === false) {
    $error = 'Kérem, egész számot adjon meg.';
  } else {
    $n = (int)$val;
    $props['parity'] = ($n % 2 === 0) ? 'páros' : 'páratlan';
    foreach ([3, 5, 7] as $d) {
      $props["div_$d"] = ($n % $d === 0) ? 'igen' : 'nem';
    }
    $props['fizzbuzz'] = ($n % 3 === 0 && $n % 5 === 0) ? 'igen' : 'nem';
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>06 – Szám tulajdonságai</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Szám tulajdonságai</h1>
  </header>

  <div class="card">
    <form method="post" action="">
      <label for="n">Egész szám</label>
      <input id="n" name="n" type="number" value="<?php echo h((string)$nRaw); ?>">
      <div style="margin-top:12px">
        <button type="submit">Vizsgálat</button>
      </div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($error === '' && $n !== null): ?>
    <div class="card ok">
      <p><strong>Vizsgált szám:</strong> <?php echo (int)$n; ?></p>
      <ul>
        <li><strong>Páros/páratlan:</strong> <?php echo h($props['parity']); ?></li>
        <li><strong>Osztható 3-mal:</strong> <?php echo h($props['div_3']); ?></li>
        <li><strong>Osztható 5-tel:</strong> <?php echo h($props['div_5']); ?></li>
        <li><strong>Osztható 7-tel:</strong> <?php echo h($props['div_7']); ?></li>
      </ul>
      <?php if ($props['fizzbuzz'] === 'igen'): ?>
        <p><span class="badge ok">Külön jelzés:</span> A szám osztható 3-mal és 5-tel is.</p>
      <?php endif; ?>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>