<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/BankAccount.php';

$owner = (string)($_POST['owner'] ?? 'Hallgató');
$initialRaw = (string)($_POST['initial'] ?? '10000');
$action = (string)($_POST['action'] ?? '');
$amountRaw = (string)($_POST['amount'] ?? '');

$errors = [];
$message = null;

// Az egyszerűség kedvéért az objektumot minden kérésben újra létrehozzuk.
// (Sessionben később tudnánk perzisztálni.)
$initial = filter_var($initialRaw, FILTER_VALIDATE_FLOAT);
if ($initial === false || $initial < 0) $initial = 0.0;

$account = new BankAccount($owner, (float)$initial); // new: objektum példányosítás

if ($_SERVER['REQUEST_METHOD'] === 'POST' && $action !== '') {
  $amount = filter_var($amountRaw, FILTER_VALIDATE_FLOAT);
  if ($amountRaw === '' || $amount === false) $errors['amount'] = 'Kérem, adjon meg érvényes összeget.';
  if ($action !== 'deposit' && $action !== 'withdraw') $errors['action'] = 'Ismeretlen művelet.';

  if (!$errors) {
    try {
      if ($action === 'deposit') $account->deposit((float)$amount);   // -> metódushívás
      if ($action === 'withdraw') $account->withdraw((float)$amount);
      $message = 'Művelet sikeres.';
    } catch (Throwable $e) {
      $message = 'Hiba: ' . $e->getMessage();
    }
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session06 / Task01 – BankAccount</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task01 – Osztály alapok: BankAccount</h1>
  </header>

  <div class="card notice">
    <p>OOP: <code>BankAccount</code> osztály privát mezőkkel, konstruktorral és metódusokkal.</p>
  </div>

  <div class="card">
    <form method="post" class="row" style="align-items:end" novalidate>
      <div>
        <label for="owner">Tulajdonos</label>
        <input id="owner" name="owner" type="text" value="<?php echo h($owner); ?>">
      </div>
      <div>
        <label for="initial">Kezdő egyenleg</label>
        <input id="initial" name="initial" type="text" value="<?php echo h($initialRaw); ?>">
      </div>
      <div>
        <label for="amount">Összeg</label>
        <input id="amount" name="amount" type="text" value="<?php echo h($amountRaw); ?>">
        <?php if (isset($errors['amount'])): ?><div class="field-error"><?php echo h($errors['amount']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="action">Művelet</label>
        <select id="action" name="action">
          <option value="">–</option>
          <option value="deposit" <?php echo $action === 'deposit' ? 'selected' : ''; ?>>Befizetés</option>
          <option value="withdraw" <?php echo $action === 'withdraw' ? 'selected' : ''; ?>>Kifizetés</option>
        </select>
        <?php if (isset($errors['action'])): ?><div class="field-error"><?php echo h($errors['action']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Végrehajt</button></div>
    </form>
  </div>

  <?php if ($message !== null): ?>
    <div class="card <?php echo str_starts_with($message, 'Hiba') ? 'err' : 'ok'; ?>">
      <strong><?php echo h($message); ?></strong>
    </div>
  <?php endif; ?>

  <div class="card">
    <h2>Aktuális állapot</h2>
    <table>
      <tr>
        <th>Tulajdonos</th>
        <td><?php echo h($account->getOwner()); ?></td>
      </tr>
      <tr>
        <th>Egyenleg</th>
        <td><?php echo h(number_format($account->getBalance(), 0, ',', ' ')); ?> Ft</td>
      </tr>
    </table>
    <p class="small">Megjegyzés: a példa nem perzisztál, frissítéskor az objektum újra létrejön a kezdő egyenlegből.</p>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>