<?php

declare(strict_types=1);
require_once __DIR__ . '/lib.php';
require_once __DIR__ . '/storage.php';

$title = 'Task07 – Újrafelhasználható JSON tároló modul';

$dataDir = ensure_data_dir();
$file = $dataDir . DIRECTORY_SEPARATOR . 'notes.json';

$text = (string)($_POST['text'] ?? '');
$errors = [];
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $text = trim($text);
  if ($text === '') $errors['text'] = 'Kérem, adjon meg szöveget.';
  elseif (mb_strlen($text, 'UTF-8') > 200) $errors['text'] = 'Maximum 200 karakter.';

  if (!$errors) {
    storage_append($file, ['id' => bin2hex(random_bytes(4)), 'text' => $text, 'at' => date('Y-m-d H:i:s')]);
    header('Location: ' . $_SERVER['PHP_SELF']); // PRG
    exit;
  }
}
if (isset($_GET['clear'])) {
  if (is_file($file)) unlink($file);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$items = storage_load($file);
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo h($title); ?></title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1><?php echo h($title); ?></h1>
  </header>

  <div class="card notice">
    <p>A JSON olvasás/írás a <code>storage.php</code> modulban van. Az oldal csak hívja a függvényeket.</p>
  </div>

  <div class="card">
    <form method="post" novalidate>
      <label for="text">Jegyzet</label>
      <input id="text" name="text" type="text" value="<?php echo h($text); ?>">
      <?php if (isset($errors['text'])): ?><div class="field-error"><?php echo h($errors['text']); ?></div><?php endif; ?>
      <div style="margin-top:12px"><button type="submit">Mentés</button></div>
    </form>
    <p class="small">Fájl: <code>data/notes.json</code> · <a href="?clear=1">Törlés</a></p>
  </div>

  <div class="card">
    <h2>Mentett jegyzetek (<?php echo (int)count($items); ?> db)</h2>
    <?php if (!$items): ?><p class="small">Nincs adat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Idő</th>
            <th>Szöveg</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach (array_reverse($items) as $it): ?>
            <tr>
              <td class="small"><?php echo h((string)$it['at']); ?></td>
              <td><?php echo h((string)$it['text']); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>