<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/Circle.php';
require_once __DIR__ . '/Rectangle.php';

$type = (string)($_POST['type'] ?? 'circle');
$rRaw = (string)($_POST['r'] ?? '5');
$aRaw = (string)($_POST['a'] ?? '3');
$bRaw = (string)($_POST['b'] ?? '4');

$errors = [];
$shape = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  if ($type === 'circle') {
    $r = filter_var($rRaw, FILTER_VALIDATE_FLOAT);
    if ($rRaw === '' || $r === false || $r < 0) $errors['r'] = 'A sugár legyen 0 vagy pozitív szám.';
    if (!$errors) $shape = new Circle((float)$r);
  } elseif ($type === 'rect') {
    $a = filter_var($aRaw, FILTER_VALIDATE_FLOAT);
    $b = filter_var($bRaw, FILTER_VALIDATE_FLOAT);
    if ($aRaw === '' || $a === false || $a < 0) $errors['a'] = 'Az A oldal legyen 0 vagy pozitív szám.';
    if ($bRaw === '' || $b === false || $b < 0) $errors['b'] = 'A B oldal legyen 0 vagy pozitív szám.';
    if (!$errors) $shape = new Rectangle((float)$a, (float)$b);
  } else {
    $errors['type'] = 'Ismeretlen alakzat.';
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session06 / Task04 – Inheritance</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task04 – Öröklődés és polimorfizmus (Shape)</h1>
  </header>

  <div class="card notice">
    <p>OOP: <code>abstract Shape</code> + <code>Circle</code>, <code>Rectangle</code>. A nézet csak a <code>Shape</code> felületet használja.</p>
  </div>

  <div class="card">
    <form method="post" novalidate>
      <label for="type">Alakzat</label>
      <select id="type" name="type">
        <option value="circle" <?php echo $type === 'circle' ? 'selected' : ''; ?>>Kör</option>
        <option value="rect" <?php echo $type === 'rect' ? 'selected' : ''; ?>>Téglalap</option>
      </select>
      <?php if (isset($errors['type'])): ?><div class="field-error"><?php echo h($errors['type']); ?></div><?php endif; ?>

      <?php if ($type === 'circle'): ?>
        <label for="r">Sugár (r)</label>
        <input id="r" name="r" type="text" value="<?php echo h($rRaw); ?>">
        <?php if (isset($errors['r'])): ?><div class="field-error"><?php echo h($errors['r']); ?></div><?php endif; ?>
      <?php else: ?>
        <div class="row">
          <div>
            <label for="a">A oldal</label>
            <input id="a" name="a" type="text" value="<?php echo h($aRaw); ?>">
            <?php if (isset($errors['a'])): ?><div class="field-error"><?php echo h($errors['a']); ?></div><?php endif; ?>
          </div>
          <div>
            <label for="b">B oldal</label>
            <input id="b" name="b" type="text" value="<?php echo h($bRaw); ?>">
            <?php if (isset($errors['b'])): ?><div class="field-error"><?php echo h($errors['b']); ?></div><?php endif; ?>
          </div>
        </div>
      <?php endif; ?>

      <div style="margin-top:12px"><button type="submit">Számítás</button></div>
    </form>
  </div>

  <?php if ($shape): ?>
    <div class="card ok">
      <h2>Eredmények</h2>
      <table>
        <tr>
          <th>Alakzat</th>
          <td><?php echo h($shape->name()); ?></td>
        </tr>
        <tr>
          <th>Terület</th>
          <td><?php echo h(number_format($shape->area(), 4, ',', ' ')); ?></td>
        </tr>
        <tr>
          <th>Kerület</th>
          <td><?php echo h(number_format($shape->perimeter(), 4, ',', ' ')); ?></td>
        </tr>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>