<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Log\FileLogger;
use App\Service\NoteService;

Autoloader::register('App', __DIR__ . '/src');

$dataDir = __DIR__ . '/data';
if (!is_dir($dataDir)) mkdir($dataDir, 0777, true);
$logFile = $dataDir . '/app.log';

$service = new NoteService(new FileLogger($logFile));

$text = (string)($_POST['text'] ?? '');
$errors = [];
$created = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  try {
    $created = $service->add($text);
    $text = '';
  } catch (Throwable $e) {
    $errors['text'] = $e->getMessage();
  }
}

$lines = is_file($logFile) ? array_slice(array_reverse(file($logFile, FILE_IGNORE_NEW_LINES)), 0, 15) : [];
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session07 / Task03 – Trait + Interface</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task03 – Trait + interface + kivételek</h1>
  </header>

  <div class="card notice">
    <p>Trait: közös mezők/metódusok. Interface: szerződés. Kivétel: <code>throw</code>/<code>catch</code>.</p>
    <p class="small">A jegyzetek memóriában élnek, a napló fájlba íródik.</p>
  </div>

  <div class="card">
    <form method="post" novalidate>
      <label for="text">Új jegyzet (max 200)</label>
      <input id="text" name="text" type="text" value="<?php echo h($text); ?>">
      <?php if (isset($errors['text'])): ?><div class="field-error"><?php echo h($errors['text']); ?></div><?php endif; ?>
      <div style="margin-top:12px"><button type="submit">Hozzáadás</button></div>
    </form>
  </div>

  <?php if ($created): ?>
    <div class="card ok">
      <strong>Jegyzet létrehozva:</strong>
      <div class="small">ID: <code><?php echo h($created->id()); ?></code> · Idő: <?php echo h($created->createdAt()); ?></div>
      <div><?php echo h($created->text()); ?></div>
    </div>
  <?php endif; ?>

  <div class="card">
    <h2>Utolsó 15 log sor</h2>
    <?php if (!$lines): ?><p class="small">Üres.</p>
    <?php else: ?><ul><?php foreach ($lines as $l): ?><li class="small"><code><?php echo h($l); ?></code></li><?php endforeach; ?></ul><?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>