<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$principalRaw = $_POST['principal'] ?? '';
$rateRaw = $_POST['rate'] ?? '';
$yearsRaw = $_POST['years'] ?? '';

$error = '';
$rows = [];
$summary = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $principal = filter_var($principalRaw, FILTER_VALIDATE_FLOAT);
  $rate = filter_var($rateRaw, FILTER_VALIDATE_FLOAT);
  $years = filter_var($yearsRaw, FILTER_VALIDATE_INT);

  if ($principal === false || $rate === false || $years === false) {
    $error = 'Kérem, érvényes adatokat adjon meg (tőke, kamat %, évek).';
  } elseif ($principal < 0 || $years < 0) {
    $error = 'A tőke és az évek száma nem lehet negatív.';
  } else {
    $capital = (float)$principal;
    $r = (float)$rate / 100.0;

    for ($year = 1; $year <= (int)$years; $year++) {
      $start = $capital;
      $interest = $start * $r;
      $end = $start + $interest;

      $rows[] = [
        'year' => $year,
        'start' => $start,
        'interest' => $interest,
        'end' => $end
      ];

      $capital = $end;
    }

    $final = $capital;
    $profit = $final - (float)$principal;

    $summary = [
      'final' => $final,
      'profit' => $profit
    ];
  }
}

function money(float $v): string
{
  return number_format($v, 2, ',', ' ') . ' Ft'; // A number_format() a számot két tizedesre formázza, vesszőt használ tizedesjelként és szóközt ezreselválasztóként, majd hozzáfűzi a „Ft” pénznemet.
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>09 – Kamatos kamat</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Kamatos kamat táblázat</h1>
  </header>

  <div class="card">
    <form method="post" action="">
      <label for="principal">Kezdőtőke</label>
      <input id="principal" name="principal" type="text" inputmode="decimal" value="<?php echo h((string)$principalRaw); ?>" placeholder="pl. 100000">

      <label for="rate">Éves kamat (%)</label>
      <input id="rate" name="rate" type="text" inputmode="decimal" value="<?php echo h((string)$rateRaw); ?>" placeholder="pl. 5.5">

      <label for="years">Évek száma</label>
      <input id="years" name="years" type="number" min="0" value="<?php echo h((string)$yearsRaw); ?>" placeholder="pl. 10">

      <div style="margin-top:12px">
        <button type="submit">Számítás</button>
      </div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($error === '' && $summary !== null): ?>
    <div class="card ok">
      <table>
        <thead>
          <tr>
            <th>Év</th>
            <th>Év eleji tőke</th>
            <th>Kamat (év)</th>
            <th>Év végi tőke</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($rows as $r): ?>
            <tr>
              <td><?php echo (int)$r['year']; ?></td>
              <td><?php echo h(money((float)$r['start'])); ?></td>
              <td><?php echo h(money((float)$r['interest'])); ?></td>
              <td><?php echo h(money((float)$r['end'])); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

      <p><strong>Végső tőke:</strong> <?php echo h(money((float)$summary['final'])); ?></p>
      <p><strong>Teljes nyereség:</strong> <?php echo h(money((float)$summary['profit'])); ?></p>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>