<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/EmailNotifier.php';
require_once __DIR__ . '/NullNotifier.php';
require_once __DIR__ . '/RegistrationService.php';

$dataDir = __DIR__ . '/data';
if (!is_dir($dataDir)) mkdir($dataDir, 0777, true);
$logFile = $dataDir . '/mails.log';

$name = (string)($_POST['name'] ?? '');
$email = (string)($_POST['email'] ?? '');
$mode = (string)($_POST['mode'] ?? 'email');

$service = new RegistrationService(
  $mode === 'null' ? new NullNotifier() : new EmailNotifier($logFile)
);

$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $res = $service->register($name, $email);
  $errors = $res['errors'];

  if ($res['ok']) {
    header('Location: ' . $_SERVER['PHP_SELF'] . '?ok=1'); // PRG
    exit;
  }
}

if (isset($_GET['clear'])) {
  if (is_file($logFile)) unlink($logFile);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$lines = is_file($logFile) ? array_slice(array_reverse(file($logFile, FILE_IGNORE_NEW_LINES)), 0, 20) : [];
$okFlash = isset($_GET['ok']);
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session06 / Task05 – Interface + DI</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task05 – Interface + Dependency Injection (Notifier)</h1>
  </header>

  <div class="card notice">
    <p>OOP: <code>Notifier</code> interface + két implementáció és egy szolgáltatás (<code>RegistrationService</code>).</p>
  </div>

  <?php if ($okFlash): ?>
    <div class="card ok"><strong>Sikeres regisztráció.</strong></div>
  <?php endif; ?>

  <div class="card">
    <form method="post" novalidate class="row" style="align-items:end">
      <div>
        <label for="name">Név</label>
        <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
        <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="email">E-mail</label>
        <input id="email" name="email" type="text" value="<?php echo h($email); ?>">
        <?php if (isset($errors['email'])): ?><div class="field-error"><?php echo h($errors['email']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="mode">Értesítés mód</label>
        <select id="mode" name="mode">
          <option value="email" <?php echo $mode === 'email' ? 'selected' : ''; ?>>EmailNotifier (log)</option>
          <option value="null" <?php echo $mode === 'null' ? 'selected' : ''; ?>>NullNotifier (nincs értesítés)</option>
        </select>
      </div>
      <div><button type="submit">Regisztráció</button></div>
    </form>
    <p class="small">EmailNotifier esetén a „küldés” csak a <code>data/mails.log</code> fájlba íródik. <a href="?clear=1">Log törlése</a></p>
  </div>

  <div class="card">
    <h2>Utolsó 20 „küldés” (log)</h2>
    <?php if (!$lines): ?><p class="small">Üres log.</p>
    <?php else: ?>
      <ul>
        <?php foreach ($lines as $l): ?><li class="small"><code><?php echo h($l); ?></code></li><?php endforeach; ?>
      </ul>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>