<?php

declare(strict_types=1);

// session_start(): elindítja a PHP session-t, így a $_SESSION tömbben perzisztens állapotot tárolhatunk a felhasználóhoz.
session_start();

/**
 * HTML-escape helper (XSS megelőzés).
 */
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/**
 * Egyszerű "flash" üzenet kezelés sessionnel:
 * - flash_set(): üzenet eltárolása a következő oldalbetöltésig
 * - flash_get(): egyszeri kiolvasás (utána törlődik)
 */
function flash_set(string $key, string $message): void
{
  $_SESSION['_flash'][$key] = $message; // $_SESSION: session változók tárolása
}
function flash_get(string $key): ?string
{
  if (!isset($_SESSION['_flash'][$key])) return null;
  $msg = (string)$_SESSION['_flash'][$key];
  unset($_SESSION['_flash'][$key]); // unset(): törli a megadott kulcsot
  return $msg;
}
?>
<?php
$note = (string)($_POST['note'] ?? '');
$error = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $note = trim($note);
  if ($note === '') {
    flash_set('error', 'Kérem, adjon meg üzenetet.');
  } else {
    // $_SESSION-ben elmentjük az utolsó üzeneteket (demó)
    $_SESSION['task05_notes'][] = [
      'text' => $note,
      'at' => date('Y-m-d H:i:s'),
    ];
    flash_set('success', 'Az üzenet elmentésre került (session).');
  }
  header('Location: ' . $_SERVER['PHP_SELF']); // PRG minta
  exit;
}

$success = flash_get('success');
$err = flash_get('error');
$notes = $_SESSION['task05_notes'] ?? [];

if (isset($_GET['clear'])) {
  unset($_SESSION['task05_notes']);
  flash_set('success', 'A lista törölve lett.');
  header('Location: ' . $_SERVER['PHP_SELF']);
  exit;
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session03 / Task05 – Flash üzenetek</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task05 – Flash üzenetek (session) + PRG minta</h1>
  </header>

  <?php if ($success): ?><div class="card ok"><?php echo h($success); ?></div><?php endif; ?>
  <?php if ($err): ?><div class="card err"><?php echo h($err); ?></div><?php endif; ?>

  <div class="card">
    <form method="post" novalidate>
      <label for="note">Üzenet</label>
      <textarea id="note" name="note" rows="3"><?php echo h($note); ?></textarea>
      <div style="margin-top:12px"><button type="submit">Mentés</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Mentett üzenetek</h2>
    <p class="small">Tárolás: session. Frissítéskor nem duplázódik a mentés a PRG (redirect) miatt.</p>
    <?php if (count($notes) === 0): ?>
      <p class="small">Nincs elem.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Időpont</th>
            <th>Üzenet</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($notes as $i => $n): ?>
            <tr>
              <td><?php echo (int)($i + 1); ?></td>
              <td><?php echo h($n['at']); ?></td>
              <td><?php echo h($n['text']); ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <p><a href="?clear=1">Lista törlése</a></p>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>