<?php

declare(strict_types=1);
require_once __DIR__ . '/lib.php';
require_once __DIR__ . '/calc.php';

$aRaw = (string)($_POST['a'] ?? '');
$bRaw = (string)($_POST['b'] ?? '');
$op = (string)($_POST['op'] ?? '+');

$errors = [];
$resultText = null;

$ops = ['+' => 'Összeadás', '-' => 'Kivonás', '*' => 'Szorzás', '/' => 'Osztás'];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $a = filter_var($aRaw, FILTER_VALIDATE_FLOAT);
  $b = filter_var($bRaw, FILTER_VALIDATE_FLOAT);

  if ($aRaw === '' || $a === false) $errors['a'] = 'Kérem, adjon meg egy érvényes számot.';
  if ($bRaw === '' || $b === false) $errors['b'] = 'Kérem, adjon meg egy érvényes számot.';
  if (!isset($ops[$op])) $errors['op'] = 'Kérem, válasszon műveletet.';

  if (!$errors) {
    $res = match ($op) {
      '+' => add((float)$a, (float)$b),
      '-' => sub((float)$a, (float)$b),
      '*' => mul((float)$a, (float)$b),
      '/' => div((float)$a, (float)$b),
      default => null
    };

    if ($res === null) $resultText = 'Hiba: 0-val nem lehet osztani.';
    else $resultText = sprintf('Eredmény: %s %s %s = %s', $a, $op, $b, $res); // sprintf(): formázott string
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session05 / Task02 – Kalkulátor modulokkal</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task02 – Kalkulátor (függvények külön fájlban)</h1>
  </header>

  <div class="card notice">
    <p>A műveletek (add/sub/mul/div) a <code>calc.php</code> fájlban vannak, az oldal csak hívja őket.</p>
  </div>

  <div class="card">
    <form method="post" novalidate class="row" style="align-items:end">
      <div>
        <label for="a">A</label>
        <input id="a" name="a" type="text" value="<?php echo h($aRaw); ?>">
        <?php if (isset($errors['a'])): ?><div class="field-error"><?php echo h($errors['a']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="op">Művelet</label>
        <select id="op" name="op">
          <?php foreach ($ops as $k => $label): ?>
            <option value="<?php echo h($k); ?>" <?php echo $op === $k ? 'selected' : ''; ?>><?php echo h($label . ' (' . $k . ')'); ?></option>
          <?php endforeach; ?>
        </select>
        <?php if (isset($errors['op'])): ?><div class="field-error"><?php echo h($errors['op']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="b">B</label>
        <input id="b" name="b" type="text" value="<?php echo h($bRaw); ?>">
        <?php if (isset($errors['b'])): ?><div class="field-error"><?php echo h($errors['b']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Számol</button></div>
    </form>
  </div>

  <?php if ($resultText !== null): ?>
    <div class="card ok"><strong><?php echo h($resultText); ?></strong></div>
  <?php elseif ($_SERVER['REQUEST_METHOD'] === 'POST' && $errors): ?>
    <div class="card err"><strong>Hiba:</strong> Kérem, javítsa a mezőket.</div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>