<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$startRaw = $_POST['start'] ?? '';
$stepRaw  = $_POST['step'] ?? '';
$countRaw = $_POST['count'] ?? '';

$error = '';
$rows = [];
$stats = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $start = filter_var($startRaw, FILTER_VALIDATE_FLOAT);
  $step  = filter_var($stepRaw, FILTER_VALIDATE_FLOAT);
  $count = filter_var($countRaw, FILTER_VALIDATE_INT);

  if ($start === false || $step === false || $count === false) {
    $error = 'Kérem, érvényes adatokat adjon meg (kezdő érték, lépésköz, elemszám).';
  } elseif ($count <= 0) {
    $error = 'Az elemszámnak pozitív egésznek kell lennie.';
  } else {
    $values = [];
    for ($i = 0; $i < (int)$count; $i++) {
      $v = (float)$start + (float)$step * $i;
      $values[] = $v;
    }

    $min = min($values);
    $max = max($values);
    $avg = array_sum($values) / count($values);

    for ($i = 0; $i < count($values); $i++) {
      $v = $values[$i];
      $square = $v * $v;
      $isEvenIntPart = (((int)floor(abs($v))) % 2 === 0) ? 'igen' : 'nem';

      $rows[] = [
        'idx' => $i,
        'value' => $v,
        'square' => $square,
        'evenIntPart' => $isEvenIntPart,
        'aboveAvg' => ($v > $avg),
      ];
    }

    $stats = ['min' => $min, 'max' => $max, 'avg' => $avg];
  }
}

function nf(float $v): string
{
  // readable number, keep up to 6 decimals but trim trailing zeros
  $s = rtrim(rtrim(number_format($v, 6, '.', ''), '0'), '.');
  return $s === '-0' ? '0' : $s;
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>10 – Sorozat + statisztika</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Mérési sorozat generálása + statisztika</h1>
  </header>

  <div class="card">
    <form method="post" action="">
      <label for="start">Kezdő érték (start)</label>
      <input id="start" name="start" type="text" inputmode="decimal" value="<?php echo h((string)$startRaw); ?>" placeholder="pl. 1.5">

      <label for="step">Lépésköz (step)</label>
      <input id="step" name="step" type="text" inputmode="decimal" value="<?php echo h((string)$stepRaw); ?>" placeholder="pl. 0.25">

      <label for="count">Elemszám (count)</label>
      <input id="count" name="count" type="number" min="1" value="<?php echo h((string)$countRaw); ?>" placeholder="pl. 12">

      <div style="margin-top:12px">
        <button type="submit">Generálás</button>
      </div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($error === '' && $stats !== null): ?>
    <div class="card ok">
      <table>
        <thead>
          <tr>
            <th>Index</th>
            <th>Érték</th>
            <th>Érték négyzete</th>
            <th>Páros-e az egészrésze?</th>
            <th>Jelzés</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($rows as $r): ?>
            <tr>
              <td><?php echo (int)$r['idx']; ?></td>
              <td><?php echo h(nf((float)$r['value'])); ?></td>
              <td><?php echo h(nf((float)$r['square'])); ?></td>
              <td><?php echo h($r['evenIntPart']); ?></td>
              <td>
                <?php if ($r['aboveAvg']): ?>
                  <span class="badge notice">above avg</span>
                <?php else: ?>
                  <span class="small">—</span>
                <?php endif; ?>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>

      <p><strong>Minimum:</strong> <?php echo h(nf((float)$stats['min'])); ?></p>
      <p><strong>Maximum:</strong> <?php echo h(nf((float)$stats['max'])); ?></p>
      <p><strong>Átlag:</strong> <?php echo h(nf((float)$stats['avg'])); ?></p>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>