<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
  $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
  if (!is_dir($dir)) {
    mkdir($dir, 0777, true);
  }
  return $dir;
}
?>
<?php
$data = ensure_dir('data');
$file = $data . DIRECTORY_SEPARATOR . 'todos.json';

function load_todos(string $file): array
{
  if (!is_file($file)) return [];
  $raw = file_get_contents($file);
  $arr = json_decode((string)$raw, true);
  return is_array($arr) ? $arr : [];
}
function save_todos(string $file, array $todos): void
{
  file_put_contents($file, json_encode($todos, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE), LOCK_EX);
}

$todos = load_todos($file);

$action = (string)($_POST['action'] ?? '');
$text = (string)($_POST['text'] ?? '');
$id = (string)($_POST['id'] ?? '');
$errors = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  if ($action === 'add') {
    $text = trim($text);
    if ($text === '') $errors['text'] = 'Kérem, adjon meg feladatot.';
    elseif (mb_strlen($text, 'UTF-8') > 120) $errors['text'] = 'Max 120 karakter.';

    if (!$errors) {
      $todos[] = ['id' => bin2hex(random_bytes(4)), 'text' => $text, 'done' => False, 'created_at' => date('Y-m-d H:i:s')];
      save_todos($file, $todos);
      header('Location: ' . $_SERVER['PHP_SELF']);
      exit;
    }
  } elseif ($action === 'toggle') {
    foreach ($todos as &$t) {
      if (($t['id'] ?? '') === $id) {
        $t['done'] = !((bool)($t['done'] ?? false));
        break;
      }
    }
    unset($t);
    save_todos($file, $todos);
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  } elseif ($action === 'delete') {
    $todos = array_values(array_filter($todos, fn($t) => ($t['id'] ?? '') !== $id));
    save_todos($file, $todos);
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  } elseif ($action === 'clear') {
    save_todos($file, []);
    header('Location: ' . $_SERVER['PHP_SELF']);
    exit;
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session04 / Task04 – Todo</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task04 – Todo lista JSON-ben</h1>
  </header>

  <div class="card">
    <form method="post" novalidate>
      <input type="hidden" name="action" value="add">
      <label for="text">Új feladat</label>
      <input id="text" name="text" type="text" value="<?php echo h($text); ?>">
      <?php if (isset($errors['text'])): ?><div class="field-error"><?php echo h($errors['text']); ?></div><?php endif; ?>
      <div style="margin-top:12px"><button type="submit">Hozzáadás</button></div>
    </form>
    <p class="small">Fájl: <code>data/todos.json</code></p>
  </div>

  <div class="card">
    <h2>Feladatok</h2>
    <?php if (!$todos): ?><p class="small">Nincs feladat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Állapot</th>
            <th>Feladat</th>
            <th>Létrehozva</th>
            <th>Művelet</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach (array_reverse($todos) as $t): ?>
            <tr>
              <td><?php echo ((bool)$t['done']) ? '<span class="badge ok">kész</span>' : '<span class="badge notice">nyitott</span>'; ?></td>
              <td><?php echo h((string)$t['text']); ?></td>
              <td class="small"><?php echo h((string)$t['created_at']); ?></td>
              <td>
                <form method="post" style="display:inline-block;margin:0">
                  <input type="hidden" name="action" value="toggle">
                  <input type="hidden" name="id" value="<?php echo h((string)$t['id']); ?>">
                  <button type="submit">Átvált</button>
                </form>
                <form method="post" style="display:inline-block;margin:0">
                  <input type="hidden" name="action" value="delete">
                  <input type="hidden" name="id" value="<?php echo h((string)$t['id']); ?>">
                  <button type="submit">Törlés</button>
                </form>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <form method="post"><input type="hidden" name="action" value="clear"><button type="submit">Összes törlése</button></form>
    <?php endif; ?>
  </div>
  <footer class="small">Generated by PHP</footer>
</body>

</html>