<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$nRaw = $_POST['n'] ?? '';
$n = null;
$error = '';
$rows = [];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $val = filter_var($nRaw, FILTER_VALIDATE_INT);
  if ($val === false) {
    $error = 'Kérem, egész számot adjon meg.';
  } else {
    $n = (int)$val;
    for ($i = 1; $i <= 10; $i++) {
      $rows[] = [$i, $n * $i];
    }
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>07 – Szorzótábla</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Szorzótábla (1–10)</h1>
  </header>

  <div class="card">
    <form method="post" action="">
      <label for="n">Szám (n)</label>
      <input id="n" name="n" type="number" value="<?php echo h((string)$nRaw); ?>">
      <div style="margin-top:12px">
        <button type="submit">Generálás</button>
      </div>
    </form>
  </div>

  <?php if ($error !== ''): ?>
    <div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div>
  <?php endif; ?>

  <?php if ($error === '' && $n !== null): ?>
    <div class="card ok">
      <p><strong>n =</strong> <?php echo (int)$n; ?></p>

      <h2>Lista</h2>
      <ul>
        <?php foreach ($rows as [$i, $res]): ?>
          <li><?php echo (int)$n; ?> × <?php echo (int)$i; ?> = <?php echo (int)$res; ?></li>
        <?php endforeach; ?>
      </ul>

      <h2>Táblázat</h2>
      <table>
        <thead>
          <tr>
            <th>Szorzó</th>
            <th>Eredmény</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($rows as [$i, $res]): ?>
            <tr>
              <td><?php echo (int)$i; ?></td>
              <td><?php echo (int)$res; ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>