<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// __DIR__: az aktuális fájl könyvtára (stabil relatív útvonalakhoz)
// mkdir(): könyvtár létrehozása, ha még nem létezik
function ensure_dir(string $name): string
{
  $dir = __DIR__ . DIRECTORY_SEPARATOR . $name;
  if (!is_dir($dir)) {
    mkdir($dir, 0777, true);
  }
  return $dir;
}
?>
<?php
$data = ensure_dir('data');
$log = $data . DIRECTORY_SEPARATOR . 'visits.log';

$line = date('Y-m-d H:i:s') .
  ' | IP=' . ($_SERVER['REMOTE_ADDR'] ?? 'unknown') .
  ' | UA=' . ($_SERVER['HTTP_USER_AGENT'] ?? 'unknown') . PHP_EOL;

// file_put_contents(): írás fájlba
// FILE_APPEND: hozzáfűzés, LOCK_EX: kizáró zárolás
file_put_contents($log, $line, FILE_APPEND | LOCK_EX);

if (isset($_GET['clear'])) {
  if (is_file($log)) unlink($log); // unlink(): fájl törlés
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$last = is_file($log) ? array_slice(array_reverse(file($log, FILE_IGNORE_NEW_LINES)), 0, 15) : [];
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session04 / Task01 – Napló</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task01 – Látogatási napló (append)</h1>
  </header>

  <div class="card notice">
    <p>Minden megnyitás hozzáfűz egy sort a <code>data/visits.log</code> fájlhoz, majd kiírja az utolsó 15 sort.</p>
  </div>

  <div class="card">
    <p><strong>Most rögzített sor:</strong> <code><?php echo h(trim($line)); ?></code></p>
    <p><a href="?clear=1">Napló törlése</a></p>
  </div>

  <div class="card">
    <h2>Utolsó bejegyzések</h2>
    <?php if (!$last): ?><p class="small">Üres.</p>
    <?php else: ?>
      <ul>
        <?php foreach ($last as $l): ?><li class="small"><code><?php echo h($l); ?></code></li><?php endforeach; ?>
      </ul>
    <?php endif; ?>
  </div>
  <footer class="small">Generated by PHP</footer>
</body>

</html>