<?php

declare(strict_types=1);

function h(string $value): string
{
  return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
  // A htmlspecialchars() HTML-speciális karaktereket (pl. <, >, ", ') biztonságos entitásokká alakít UTF-8 kódolással, megelőzve az XSS támadásokat.
}

$name = "Minta Elek";
$neptun = "ABC123";
$age = 19;
$favoriteLanguage = "PHP";

$adultLabel = ($age >= 18) ? "adult" : "minor";
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>02 – Változók: Student Card</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Student card</h1>
  </header>

  <div class="card">
    <h2><?php echo h($name); ?>
      <span class="badge <?php echo ($adultLabel === 'adult') ? 'ok' : 'notice'; ?>">
        <?php echo h($adultLabel); ?>
      </span>
    </h2>
    <table>
      <tr>
        <th>Neptun</th>
        <td><?php echo h($neptun); ?></td>
      </tr>
      <tr>
        <th>Életkor</th>
        <td><?php echo (int)$age; ?></td>
      </tr>
      <tr>
        <th>Kedvenc nyelv</th>
        <td><?php echo h($favoriteLanguage); ?></td>
      </tr>
    </table>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>