<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Domain\Temperature;

Autoloader::register('App', __DIR__ . '/src');

$mode = (string)($_POST['mode'] ?? 'c2f');
$valueRaw = (string)($_POST['value'] ?? '');
$errors = [];
$result = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $v = filter_var($valueRaw, FILTER_VALIDATE_FLOAT);
  if ($valueRaw === '' || $v === false) $errors['value'] = 'Kérem, adjon meg érvényes számot.';
  if ($mode !== 'c2f' && $mode !== 'f2c') $errors['mode'] = 'Ismeretlen mód.';

  if (!$errors) {
    $temp = ($mode === 'c2f') ? Temperature::fromCelsius((float)$v) : Temperature::fromFahrenheit((float)$v);
    $result = ['c' => $temp->celsius(), 'f' => $temp->fahrenheit()];
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session07 / Task01 – Namespace + Autoload</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task01 – Namespace + autoload</h1>
  </header>

  <div class="card notice">
    <p>Az osztályok <code>src/</code> alatt namespace-ekbe vannak rendezve, és egy egyszerű autoloader tölti be őket.</p>
  </div>

  <div class="card">
    <form method="post" novalidate class="row" style="align-items:end">
      <div>
        <label for="mode">Átváltás</label>
        <select id="mode" name="mode">
          <option value="c2f" <?php echo $mode === 'c2f' ? 'selected' : ''; ?>>Celsius → Fahrenheit</option>
          <option value="f2c" <?php echo $mode === 'f2c' ? 'selected' : ''; ?>>Fahrenheit → Celsius</option>
        </select>
        <?php if (isset($errors['mode'])): ?><div class="field-error"><?php echo h($errors['mode']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="value">Érték</label>
        <input id="value" name="value" type="text" value="<?php echo h($valueRaw); ?>">
        <?php if (isset($errors['value'])): ?><div class="field-error"><?php echo h($errors['value']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Számítás</button></div>
    </form>
  </div>

  <?php if ($result): ?>
    <div class="card ok">
      <h2>Eredmény</h2>
      <table>
        <tr>
          <th>Celsius</th>
          <td><?php echo h(number_format((float)$result['c'], 2, ',', ' ')); ?> °C</td>
        </tr>
        <tr>
          <th>Fahrenheit</th>
          <td><?php echo h(number_format((float)$result['f'], 2, ',', ' ')); ?> °F</td>
        </tr>
      </table>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>