<?php

declare(strict_types=1);
require_once __DIR__ . '/lib.php';
require_once __DIR__ . '/validators.php';

$name = (string)($_POST['name'] ?? '');
$email = (string)($_POST['email'] ?? '');
$ageRaw = (string)($_POST['age'] ?? '');

$errors = [];
$data = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  if ($e = validate_required($name, 'Kérem, adja meg a nevét.')) $errors['name'] = $e;
  if ($e = validate_email($email, 'Kérem, adja meg az e-mail címét.')) $errors['email'] = $e;
  if ($e = validate_int_range($ageRaw, 0, 120, 'Az életkor 0 és 120 közötti egész legyen.')) $errors['age'] = $e;

  if (!$errors) {
    $data = ['name' => trim($name), 'email' => trim($email), 'age' => (int)$ageRaw];
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session05 / Task03 – Validáció modul</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task03 – Validációs függvények külön fájlban</h1>
  </header>

  <div class="card notice">
    <p>A mezőellenőrzések a <code>validators.php</code> fájlban vannak, a főoldal csak felhasználja őket.</p>
  </div>

  <div class="card">
    <form method="post" novalidate>
      <div class="row">
        <div>
          <label for="name">Név</label>
          <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
          <?php if (isset($errors['name'])): ?><div class="field-error"><?php echo h($errors['name']); ?></div><?php endif; ?>
        </div>
        <div>
          <label for="age">Életkor</label>
          <input id="age" name="age" type="number" min="0" max="120" value="<?php echo h($ageRaw); ?>">
          <?php if (isset($errors['age'])): ?><div class="field-error"><?php echo h($errors['age']); ?></div><?php endif; ?>
        </div>
      </div>
      <label for="email">E-mail</label>
      <input id="email" name="email" type="text" value="<?php echo h($email); ?>">
      <?php if (isset($errors['email'])): ?><div class="field-error"><?php echo h($errors['email']); ?></div><?php endif; ?>

      <div style="margin-top:12px"><button type="submit">Beküldés</button></div>
    </form>
  </div>

  <?php if ($data): ?>
    <div class="card ok">
      <h2>Összefoglaló</h2>
      <ul>
        <li>Név: <?php echo h($data['name']); ?></li>
        <li>E-mail: <?php echo h($data['email']); ?></li>
        <li>Életkor: <?php echo (int)$data['age']; ?></li>
      </ul>
    </div>
  <?php endif; ?>

  <footer class="small">Generated by PHP</footer>
</body>

</html>