<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/Cart.php';

$catalog = [
  new Product('p1', 'Kenyér', 899),
  new Product('p2', 'Tej', 499),
  new Product('p3', 'Sajt', 1299),
];

$cart = new Cart();

$selected = (string)($_POST['product'] ?? 'p1');
$qtyRaw = (string)($_POST['qty'] ?? '1');
$errors = [];
$info = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $qty = filter_var($qtyRaw, FILTER_VALIDATE_INT);
  if ($qtyRaw === '' || $qty === false) $errors['qty'] = 'Kérem, adjon meg egész mennyiséget.';
  if (!in_array($selected, array_map(fn($p) => $p->id(), $catalog), true)) $errors['product'] = 'Ismeretlen termék.';

  if (!$errors) {
    $p = null;
    foreach ($catalog as $prod) if ($prod->id() === $selected) {
      $p = $prod;
      break;
    }
    try {
      $cart->add($p, (int)$qty);
      $info = 'A termék kosárba került (demó kosár: csak ebben a kérésben él).';
    } catch (Throwable $e) {
      $info = 'Hiba: ' . $e->getMessage();
    }
  }
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session06 / Task02 – Product/Cart</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task02 – Osztályok együtt: Product + Cart</h1>
  </header>

  <div class="card notice">
    <p>OOP: több osztály együttműködése (Product → CartItem → Cart).</p>
  </div>

  <div class="card">
    <form method="post" class="row" style="align-items:end" novalidate>
      <div>
        <label for="product">Termék</label>
        <select id="product" name="product">
          <?php foreach ($catalog as $p): ?>
            <option value="<?php echo h($p->id()); ?>" <?php echo $selected === $p->id() ? 'selected' : ''; ?>>
              <?php echo h($p->name()); ?> (<?php echo (int)$p->priceFt(); ?> Ft)
            </option>
          <?php endforeach; ?>
        </select>
        <?php if (isset($errors['product'])): ?><div class="field-error"><?php echo h($errors['product']); ?></div><?php endif; ?>
      </div>
      <div>
        <label for="qty">Mennyiség</label>
        <input id="qty" name="qty" type="number" min="1" max="999" value="<?php echo h($qtyRaw); ?>">
        <?php if (isset($errors['qty'])): ?><div class="field-error"><?php echo h($errors['qty']); ?></div><?php endif; ?>
      </div>
      <div><button type="submit">Kosárba</button></div>
    </form>
  </div>

  <?php if ($info !== null): ?>
    <div class="card <?php echo str_starts_with($info, 'Hiba') ? 'err' : 'ok'; ?>"><strong><?php echo h($info); ?></strong></div>
  <?php endif; ?>

  <div class="card">
    <h2>Kosár tartalma (demó)</h2>
    <?php $items = $cart->items(); ?>
    <?php if (!$items): ?><p class="small">A kosár üres.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Termék</th>
            <th>Egységár</th>
            <th>Mennyiség</th>
            <th>Részösszeg</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($items as $it): ?>
            <tr>
              <td><?php echo h($it->product()->name()); ?></td>
              <td><?php echo (int)$it->product()->priceFt(); ?> Ft</td>
              <td><?php echo (int)$it->qty(); ?></td>
              <td><?php echo (int)$it->subtotalFt(); ?> Ft</td>
            </tr>
          <?php endforeach; ?>
        </tbody>
        <tfoot>
          <tr>
            <th colspan="3">Összesen</th>
            <th><?php echo (int)$cart->totalFt(); ?> Ft</th>
          </tr>
        </tfoot>
      </table>
    <?php endif; ?>
    <p class="small">Megjegyzés: session nélkül a kosár nem marad meg új kérésre.</p>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>