<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/src/Utils/Autoloader.php';

use App\Utils\Autoloader;
use App\Repo\JsonStudentRepository;
use App\Service\StudentService;

Autoloader::register('App', __DIR__ . '/src');

$dataDir = __DIR__ . '/data';
if (!is_dir($dataDir)) mkdir($dataDir, 0777, true);
$file = $dataDir . '/students.json';

$service = new StudentService(new JsonStudentRepository($file));

$name = (string)($_POST['name'] ?? '');
$neptun = (string)($_POST['neptun'] ?? '');
$action = (string)($_POST['action'] ?? '');
$errors = [];
$flash = isset($_GET['ok']) ? 'Sikeres mentés.' : null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  try {
    if ($action === 'add') {
      $service->add($name, $neptun);
      header('Location: ' . $_SERVER['PHP_SELF'] . '?ok=1');
      exit;
    }
    if ($action === 'delete') {
      $id = (string)($_POST['id'] ?? '');
      $service->delete($id);
      header('Location: ' . $_SERVER['PHP_SELF']);
      exit;
    }
  } catch (Throwable $e) {
    $errors['form'] = $e->getMessage();
  }
}

if (isset($_GET['clear'])) {
  if (is_file($file)) unlink($file);
  header('Location: ' . strtok($_SERVER['REQUEST_URI'], '?'));
  exit;
}

$q = trim((string)($_GET['q'] ?? ''));
$sort = (string)($_GET['sort'] ?? 'name_asc');
$items = $service->list($q, $sort);
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session07 / Task04 – Repository</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task04 – Repository minta + JSON perzisztencia</h1>
  </header>

  <div class="card notice">
    <p><code>StudentRepository</code> interface + JSON implementáció + <code>StudentService</code>.</p>
    <p class="small">Fájl: <code>data/students.json</code> · <a href="?clear=1">Törlés</a></p>
  </div>

  <?php if ($flash): ?><div class="card ok"><strong><?php echo h($flash); ?></strong></div><?php endif; ?>
  <?php if (isset($errors['form'])): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($errors['form']); ?></div><?php endif; ?>

  <div class="card">
    <h2>Új hallgató</h2>
    <form method="post" class="row" style="align-items:end" novalidate>
      <input type="hidden" name="action" value="add">
      <div>
        <label for="name">Név</label>
        <input id="name" name="name" type="text" value="<?php echo h($name); ?>">
      </div>
      <div>
        <label for="neptun">Neptun (6)</label>
        <input id="neptun" name="neptun" type="text" value="<?php echo h($neptun); ?>">
      </div>
      <div><button type="submit">Mentés</button></div>
    </form>
  </div>

  <div class="card">
    <h2>Lista</h2>
    <form method="get" class="row" style="align-items:end">
      <div>
        <label for="q">Keresés</label>
        <input id="q" name="q" type="text" value="<?php echo h($q); ?>">
      </div>
      <div>
        <label for="sort">Rendezés</label>
        <select id="sort" name="sort">
          <option value="name_asc" <?php echo $sort === 'name_asc' ? 'selected' : ''; ?>>Név A→Z</option>
          <option value="name_desc" <?php echo $sort === 'name_desc' ? 'selected' : ''; ?>>Név Z→A</option>
          <option value="neptun_asc" <?php echo $sort === 'neptun_asc' ? 'selected' : ''; ?>>Neptun A→Z</option>
          <option value="neptun_desc" <?php echo $sort === 'neptun_desc' ? 'selected' : ''; ?>>Neptun Z→A</option>
        </select>
      </div>
      <div><button type="submit">Szűrés</button></div>
    </form>

    <p class="small">Találatok: <?php echo (int)count($items); ?></p>

    <?php if (!$items): ?><p class="small">Nincs adat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>Név</th>
            <th>Neptun</th>
            <th>Művelet</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($items as $s): ?>
            <tr>
              <td><?php echo h($s->name()); ?></td>
              <td><code><?php echo h($s->neptun()); ?></code></td>
              <td>
                <form method="post" style="margin:0">
                  <input type="hidden" name="action" value="delete">
                  <input type="hidden" name="id" value="<?php echo h($s->id()); ?>">
                  <button type="submit">Törlés</button>
                </form>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>