<?php

declare(strict_types=1);

// htmlspecialchars(): HTML-escape (XSS megelőzés)
function h(string $v): string
{
  return htmlspecialchars($v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}
?>
<?php

declare(strict_types=1);

require_once __DIR__ . '/db.php';

$q = trim((string)($_GET['q'] ?? ''));
$pageRaw = (string)($_GET['page'] ?? '1');
$page = max(1, (int)filter_var($pageRaw, FILTER_VALIDATE_INT) ?: 1);
$perPage = 5;

$error = null;
$rows = [];
$total = 0;

try {
  $mysqli = db();

  $like = '%' . $q . '%';

  // COUNT (prepared)
  $stmt = $mysqli->prepare('SELECT COUNT(*) AS c FROM products WHERE name LIKE ?');
  $stmt->bind_param('s', $like);
  $stmt->execute();
  $res = $stmt->get_result();
  $total = (int)($res->fetch_assoc()['c'] ?? 0);
  $stmt->close();

  $pages = max(1, (int)ceil($total / $perPage));
  if ($page > $pages) $page = $pages;

  $offset = ($page - 1) * $perPage;

  // LIST (prepared LIMIT/OFFSET)
  $stmt = $mysqli->prepare('SELECT id, name, price_ft FROM products WHERE name LIKE ? ORDER BY name LIMIT ? OFFSET ?');
  $stmt->bind_param('sii', $like, $perPage, $offset);
  $stmt->execute();
  $res = $stmt->get_result();
  $rows = $res->fetch_all(MYSQLI_ASSOC);
  $stmt->close();

  $mysqli->close();
} catch (Throwable $e) {
  $error = $e->getMessage();
}

function pageLink(int $p, string $q): string
{
  return '?q=' . urlencode($q) . '&page=' . $p;
}
?>
<!doctype html>
<html lang="hu">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Session09 / Task04 – Keresés + lapozás</title>
  <link rel="stylesheet" href="style.css">
</head>

<body>
  <header>
    <h1>Task04 – Keresés + lapozás (LIKE + LIMIT/OFFSET)</h1>
  </header>

  <div class="card notice">
    <p>Feladat: termékek keresése név alapján (<code>LIKE</code>) és lapozás (<code>LIMIT/OFFSET</code>) prepared statement-tel.</p>
  </div>

  <?php if ($error): ?><div class="card err"><strong>Hiba:</strong> <?php echo h($error); ?></div><?php endif; ?>

  <div class="card">
    <form method="get" class="row" style="align-items:end">
      <div>
        <label for="q">Keresés (név részlet)</label>
        <input id="q" name="q" type="text" value="<?php echo h($q); ?>">
      </div>
      <div><button type="submit">Keresés</button></div>
    </form>
    <p class="small">Találatok: <strong><?php echo (int)$total; ?></strong></p>
  </div>

  <div class="card">
    <h2>Lista</h2>
    <?php if (!$rows): ?><p class="small">Nincs találat.</p>
    <?php else: ?>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Név</th>
            <th>Ár</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($rows as $r): ?>
            <tr>
              <td><?php echo (int)$r['id']; ?></td>
              <td><?php echo h((string)$r['name']); ?></td>
              <td><?php echo h(number_format((int)$r['price_ft'], 0, ',', ' ')); ?> Ft</td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    <?php endif; ?>

    <?php
    $pages = max(1, (int)ceil($total / $perPage));
    ?>
    <div class="small">
      Oldal:
      <?php for ($p = 1; $p <= $pages; $p++): ?>
        <?php if ($p === $page): ?>
          <strong><?php echo $p; ?></strong>
        <?php else: ?>
          <a href="<?php echo h(pageLink($p, $q)); ?>"><?php echo $p; ?></a>
        <?php endif; ?>
        <?php if ($p < $pages) echo ' · '; ?>
      <?php endfor; ?>
    </div>
  </div>

  <footer class="small">Generated by PHP</footer>
</body>

</html>